Search, One-page forms and User mgmt section review
ezsystems/commerce-documentation pull request #10
Opened 2020-06-10 06:48 UTC by DominikaK

Note: `Field`/`field` distinction left on purpose, the search section refers to Solr fields (lowercase) a lot.

2020-06-10 06:49 UTC, DominikaK commented on docs/guide/user_management/customer_center/customer_center_installation_and_configuration.md
> +# Customer center installation
Note: this page will probably be changed completely once we know how the Customer center will be integrated into Commerce

2020-06-16 12:39 UTC, MagdalenaZuba requested changes

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/implement_custom_one_page_form.md
> +This sends as email to the shop administrator.
```suggestion
This invokes an email to the shop administrator.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/implement_custom_one_page_form.md
> +You should define this type as a service, so you can inject any logic that you need.
```suggestion
You define this type as a service, so you can inject any logic that you need.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/implement_custom_one_page_form.md
> +See [How to render Symfony forms](https://symfony.com/doc/current/form/form_customization.html) for more information.
```suggestion
See [How to render Symfony forms](https://symfony.com/doc/3.4/form/form_customization.html) for more information.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms.md
> +eZ Commerce uses the [Symfony forms](http://symfony.com/doc/current/forms.html) as a part of the solution,
```suggestion
eZ Commerce uses the [Symfony forms](http://symfony.com/doc/3.4/forms.html) as a part of the solution,
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms.md
> +You can differ between valid and invalid responses and change the behavior according your needs.
```suggestion
You can differ between valid and invalid responses and change the behavior according to your needs.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms.md
> +Usually a confirmation page is displayed, but you can choose one of following behaviors:
```suggestion
Usually a confirmation page is displayed, but you can choose one of the following behaviors:
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms_api/dataprocessors/events_before_and_after_a_dataprocessor.md
> +In your class you can access and manipulate the normalized `FormEntity`:
```suggestion
In the implemented class you can access and manipulate the normalized `FormEntity`:
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms_api/dataprocessors/events_before_and_after_a_dataprocessor.md
> +If you manipulate the normalized entity, remember that it effect the next `DataProcessors`.
```suggestion
If you manipulate the normalized entity, remember that it effects the next `DataProcessors`.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms_api/one_page_forms_api.md
> +Besides standard [Symfony validators,](http://symfony.com/doc/current/validation.html)
```suggestion
Besides standard [Symfony validators,](http://symfony.com/doc/3.4/validation.html)
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms_api/one_page_forms_api.md
> +A phone and/or fax validator verify a valid number format. The folowing formats are supported:
```suggestion
A phone and/or fax validator verifies a valid number format. The following formats are supported:
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms_templates.md
> +|`invoice.html.twig`|Renders update the invoice address form|
```suggestion
|`invoice.html.twig`|Renders the update the invoice address form|
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search.md
> +URLs are unique, so you can share a link to a search result
```suggestion
URLs are unique, so you can share a link to a search result.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_configuration/solr_schema_configuration.md
> +The following changes are applies:
```suggestion
The following changes are applied:
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/custom_search.md
> +        // 8. Finally we perform the search.
```suggestion
        // 8. Perform the search
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/custom_search.md
> +        // 5. Add offset and limit.
```suggestion
        // 5. Add offset and limit
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms_api/one_page_forms_api.md
> +The post code (ZIP) validation rules are different for each country.
```suggestion
The ZIP code validation rules are different for each country.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms_api/one_page_forms_api.md
> +To define the different code pattern for each post code a new service is defined.
```suggestion
To define the different code pattern for each ZIP code a new service is defined.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/one_page_forms/one_page_forms_api/one_page_forms_api.md
> +    This validator validates the post code based on the submitted country.
```suggestion
    This validator validates the ZIP code based on the submitted country.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/custom_search.md
> +        // 9. The hits could be found here
```suggestion
        // 9. The hits can be found here
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/custom_search.md
> +`ContentNameSorting` - sorting by content Field name in a given direction.
```suggestion
`ContentNameSorting` - sorts the results by content Field name in a given direction.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/indexer_plugin_for_custom_field_types.md
> +It enables indexing additional data Solr. For example, it enables searching with additional complex data type like specification matrix, variant matrix, etc., as conditions.
```suggestion
It enables indexing additional data with Solr. For example, it enables searching with additional complex data type like specification matrix, variant matrix, etc., as conditions.
```
???

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/indexer_plugin_for_custom_field_types.md
> +
```suggestion
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/indexer_plugin_for_custom_field_types.md
> +If you want to test how your new fields looks like in Solr you have to run the reindex command
```suggestion
If you want to test how your new fields look like in Solr you have to run the reindex command
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/indexer_plugin_for_custom_field_types.md
> +The select your collection (usually `collection1`) and then select query.
```suggestion
Then select your collection (usually `collection1`) and select a query.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/modifying_the_search_query.md
> +This event listener handles this situation.
```suggestion
The event listener handles this situation.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/solr_managed_resources.md
> +    For more information about Solr managed resources, see [Solr documentation](https://lucene.apache.org/solr/guide/7_1/managed-resources.html).
```suggestion
    For more information about Solr managed resources, see [Solr documentation.](https://lucene.apache.org/solr/guide/7_1/managed-resources.html)
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/solr_managed_resources.md
> +This definition should be placed in `schema.xml` files. It defines `solr.ManagedSynonymFilterFactory` for synonym main class instead of `SynonymFilterFactory`.
```suggestion
This definition should be placed in `schema.xml` file. It defines `solr.ManagedSynonymFilterFactory` for synonym main class instead of `SynonymFilterFactory`.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/solr_managed_resources.md
> +With the current version of Solr, if you use managed synonyms you have to use to one-to-many synonyms definition.
```suggestion
With the current version of Solr, if you use managed synonyms you have to use the one-to-many synonyms definition.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/using_solr_spellcheck.md
> +Make sure you have also this element in the XML file:
```suggestion
Make sure you have also the following element in the XML file:
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_cookbook/using_solr_spellcheck.md
> +but spellcheck should albo work with the default values.
```suggestion
but spellcheck should also work with the default values.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_faq.md
> +eZ Commerce uses the Solr version [recommended by Ibexa](https://doc.ezplatform.com/en/latest/getting_started/requirements/).
```suggestion
eZ Commerce uses the Solr version [recommended by Ibexa](https://doc.ezplatform.com/en/2.5/getting_started/requirements/).
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_faq.md
> +It depends ono the configuration. If Solr is configured to auto-commit, the index is removed.
```suggestion
It depends on the configuration. If Solr is configured to auto-commit, the index is removed.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_features/search_autosuggest/adding_elements_to_autosuggestion.md
> +In this example you display a flag with for new products.
```suggestion
In this example you display a flag for new products.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_features/search_indexing/indexing_email_data.md
> +The User Field Type don't have an implementation of `SearchField`, so this `SearchField` class must implement the `Indexable` interface.
```suggestion
The User Field Type doesn't have an implementation of `SearchField`, so this `SearchField` class must implement the `Indexable` interface.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_features/search_indexing/indexing_file_content.md
> +Apache Tika has two available modes: Server Mode and App Mode. eZ Commerce are using Apache Tika in App mode.
```suggestion
Apache Tika has two available modes: Server Mode and App Mode. eZ Commerce is using Apache Tika in App mode.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_features/search_indexing/indexing_file_content.md
> +    and its bundle is enabled in the kernel.
```suggestion
    and is enabled in the kernel.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/search/search_features/search_indexing/indexing_file_content.md
> +    and the Apache user, because the indexer is triggered after a file is modified modification in the backend.
```suggestion
    and the Apache user, because the indexer is triggered after a file is modified in the backend.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/access_control.md
> +`VerifyUserPoliciesRequestListener.php` listens to a `kernel.finish_request` event,
```suggestion
`VerifyUserPoliciesRequestListener.php` listens to a `kernel.finish_request` event.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_and_erp.md
> +|`ElectronicMail`|Email address of this person|
```suggestion
|`ElectronicMail`|Email address|
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_api/contentserviceinterface.md
> +|`getMainContacts($customerNumber)`|Get the list of main contacts for a given customer number|
```suggestion
|`getMainContacts($customerNumber)`|Gets the list of main contacts for a given customer number|
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_api/formprocessorinterface.md
> +CheckUserEmailFormProcessor checks if a User with given email address already exists in the company structure.
```suggestion
`CheckUserEmailFormProcessor` checks if a User with given email address already exists in the company structure.  
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_api/initialformvaluesserviceinterface.md
> +The given `$formAttributes` define the attribute names that are suppose to be fetched and returned with values:
```suggestion
The given `$formAttributes` defines the attribute names that are suppose to be fetched and returned with values:
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_api/initialformvaluesserviceinterface.md
> +`InitialAddUserValuesService` tries to pre-fill `customer_number` and `contact_number` from the query parameters of the request and assigns the values to the `add_user` form array.
```suggestion
`InitialAddUserValuesService` tries to pre-fill `customer_number` and `contact_number` from the query parameters of the request and assign the values to the `add_user` form array.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_api/initialformvaluesserviceinterface.md
> +`InitialEditUserValuesService` loads content from an User Content item and assigns the values to the `edit_user` form array.
```suggestion
`InitialEditUserValuesService` loads content from a User Content item and assigns the values to the `edit_user` form array.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_cookbook.md
> +3\. Add validation and other settings. The options depends on the form field type.
```suggestion
3\. Add validation and other settings. The options depend on the form field type.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_functions/customer_center_functions.md
> +The Customer center is visible for users only if you have the rights for it.
```suggestion
The Customer center is visible for users only if they have the rights for it.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_functions/customer_center_functions.md
> +The list displayed on the entry page shows
```suggestion
The list displayed on the entry page shows:
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_functions/customer_center_functions.md
> +You cannow change the customer number and contact number. After storing the form, the user gets a shop account.
```suggestion
You cannot change the customer number and contact number. After storing the form, the user gets a shop account.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_functions/customer_center_user_actions.md
> +You can change the [form field type](http://symfony.com/doc/current/reference/forms/types.html).
```suggestion
You can change the [form field type.](http://symfony.com/doc/3.4/reference/forms/types.html)
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_functions/customer_center_user_actions.md
> +The configuration value must a valid service ID and the service's class must implement [`InitialFormValuesServiceInterface`](../customer_center_api/initialformvaluesserviceinterface.md).
```suggestion
The configuration value must be a valid service ID and the service's class must implement [`InitialFormValuesServiceInterface`](../customer_center_api/initialformvaluesserviceinterface.md).
```
OR
```suggestion
The configuration value must have a valid service ID and the service's class must implement [`InitialFormValuesServiceInterface`](../customer_center_api/initialformvaluesserviceinterface.md).
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_functions/customer_center_user_actions.md
> +They are executed sequentially according the order of definition in the configuration.
```suggestion
They are executed sequentially according to the order of definition in the configuration.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/token/token.md
> +After user registration a token is created a stored in the database. The token is valid for a specific time.
```suggestion
After user registration a token is created and stored in the database. The token is valid for a specific time.
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/token/token.md
> +|`actionServiceMethod`|string|yes|Name of the service method that is invoked|
```suggestion
|`actionServiceMethod`|string|yes|Name of the service method that is invoked.|
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/token/token.md
> +|`actionServiceMethodParameter`|eZ\Publish\Core\Repository\Values\User\User|yes|Parameter for the service method|
```suggestion
|`actionServiceMethodParameter`|eZ\Publish\Core\Repository\Values\User\User|yes|Parameter for the service method.|
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/token/token.md
> +If you have cannot inject the service, you can use the container:
```suggestion
If you cannot inject the service, you can use the container:
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/token/tokencontroller.md
> +Each token as has the following attributes to process the token-specific logic:
```suggestion
Each token has the following attributes to process the token-specific logic:
```

2020-06-16 12:39 UTC, MagdalenaZuba commented on docs/guide/user_management/token/tokencontroller.md
> +Inside the token controller `TokenServiceMethodProcessorService` implements the custom logic for each token.
```suggestion
Inside the token `TokenServiceMethodProcessorService` controller implements the custom logic for each token.
```

2020-06-16 12:42 UTC, DominikaK commented on docs/guide/one_page_forms/one_page_forms_api/dataprocessors/events_before_and_after_a_dataprocessor.md
> +If you manipulate the normalized entity, remember that it effect the next `DataProcessors`.
```suggestion
If you manipulate the normalized entity, remember that it affects the next `DataProcessors`.
```

2020-06-16 12:47 UTC, DominikaK commented on docs/guide/search/search_features/search_indexing/indexing_file_content.md
> +Apache Tika has two available modes: Server Mode and App Mode. eZ Commerce are using Apache Tika in App mode.
```suggestion
Apache Tika has two available modes: Server Mode and App Mode. eZ Commerce uses Apache Tika in App mode.
```

2020-06-16 12:49 UTC, DominikaK commented on docs/guide/one_page_forms/implement_custom_one_page_form.md
> +This sends as email to the shop administrator.
```suggestion
An email is then sent to the shop administrator.
```

2020-06-16 12:53 UTC, MagdalenaZuba approved these changes

2020-06-16 13:01 UTC, merged