EC-126: Replaced SilversolutionsDatatypesBundle with IbexaPlatformCommerceFieldTypesBundle
ezsystems/commerce-documentation pull request #15
Opened 2020-07-13 13:22 UTC by DominikaK

https://jira.ez.no/browse/EC-126

2020-07-22 13:41 UTC, ViniTou requested changes

2020-07-22 13:41 UTC, ViniTou commented on docs/guide/search/search_features/search_indexing/indexing_file_content.md
> +In order to extend the indexer for files you have to extend the `Ibexa\Platform\Commerce\FieldTypes\FieldType\BinaryFile` service.
```suggestion
In order to extend the indexer for files you have to extend the `Ibexa\Platform\Commerce\FieldTypes\FieldType\BinaryFile\SearchField` service.
```

2020-07-22 13:41 UTC, ViniTou commented on docs/api/field_type_reference/sesprofiledata.md
> +            - { name: ezpublish.storageEngine.legacy.converter, alias: sesprofiledata }
missing :
```
    Ibexa\Platform\Commerce\FieldTypes\FieldType\SesProfileData\Type:
        tags:
            - { name: ezpublish.fieldType, alias: sesprofiledata }
```

2020-07-22 13:41 UTC, ViniTou commented on docs/api/field_type_reference/sesexternaldata.md
> +            - { name: ezpublish.storageEngine.legacy.converter, alias: sesexternaldata }
missing:
```
    Ibexa\Platform\Commerce\FieldTypes\FieldType\SesExternalData\Type:
        tags:
            - { name: ezpublish.fieldType, alias: sesexternaldata }

    Ibexa\Platform\Commerce\FieldTypes\FieldType\SesExternalData\SearchField:
        arguments:
            $configResolver: '@ezpublish.config.resolver'
        calls:
            - [ setIndexDefinition ]
        tags:
            - { name: ezpublish.fieldType.indexable, alias: sesexternaldata }
```

2020-07-28 09:04 UTC, ViniTou approved these changes

2020-07-30 06:17 UTC, MagdalenaZuba approved these changes

2020-07-30 06:41 UTC, merged