EC-84: Restructure eZ Commerce doc, part 2
ezsystems/commerce-documentation pull request #2
Opened 2020-05-06 08:10 UTC by DominikaK

https://jira.ez.no/browse/EC-84

- Removes glossary and irrelevant release notes
- (Partially) replaces silver e-shop naming with eZ Commerce
- (Partially) unifies terminology
- Generally cleans up text and removes some duplicated content

2020-05-11 08:29 UTC, dabrt requested changes
Please review my comments and suggestions.

2020-05-11 08:29 UTC, dabrt commented on docs/api/rest_api.md
> +eZ Commerce extends the Rest API of eZ Platform with:
I think I saw "eZ Platform REST API" elsewhere and I like it better than "Rest API of eZ Platform". Also -for consistency, I'd decide on one version and use it.
Also, I think the sentence that introduces a bulleted list would look more elegant if it ended with "the following sth". For example:
eZ Commerce extends the eZ Platform Rest API with the following features:

2020-05-11 08:29 UTC, dabrt commented on docs/cookbook/frontend_customizing/4_front_end_stack_in_details/4.2_customized_foundation_framework/4.2._customized_foundation_framework.md
> +If you need some features from the higher eZ Commerce version, you will need to create the templates by yourself.
I'd go along the lines of:
If you need features from the newer version of eZ Commerce, you must create the templates by yourself.
This way we avoid a repetition of "need". Also, when I look at a broader picture, I'd add another sentence that tells the users how they could create the templates.
For more information about adding templates, see [Adding tempates](https://doc.ezplatform.com/en/master/tutorials/extending_admin_ui/4_adding_a_custom_tag/#create-a-template).
If the table below lists available templates, I'd add a sentence that introduces the table, something like:
For a list of available templates, see the table below.
If the sass files is something different, I's add a sentence or two of an explanation.

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/first_steps.md
> +# First steps
Is "First steps" used consistently throughout the docs? I saw "Getting started" and "First steps" in almost equal proportions in the search results. if such sections do not differ in function, I'd choose one option from the two.

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/installation.md
> +Make sure that you have setup proper auth parameters for the updates.ez.no update server. You will receive the login parameters from the customer portal at ez.no:
Per our terminology "setup" is a noun, while "set up" is a verb. I'd also spell out "authentication" to avoid jargon. If authentication parameters and login parameters are the same, I would choose one option and apply it consistently. Also - I would remove "will" and simply inform the user that "You receive the ... parmeters..."

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/installation_and_configuration_faqs.md
> +- You have configured the correct webconnector URL: `webconnector_url: ''`
For future consideration - If we followed STE recommendations, we would not use present perfect and resort to simple past only. This increases chances for content reuse and legibility if the reader is not English-speaking.
webconnector is name of a proprietary piece of software. Is it what you mean here? Or should it be "web connector"?

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/installation_and_configuration_faqs.md
> +You need to generate a secret using `./vendor/defuse/php-encryption/bin/generate-defuse-key`
I would consider writing "You must generate a secret by using the following utility:" or even "Generate a secret by using the following utility:"

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/installation_and_configuration_faqs.md
> +You can configure it in `parameters.yml`:
I would consider writing "Then configure the secret in the `parameters.yml` file:"

("You can" implies that there are other places where the secret can be configured.)

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
>  eZ Commerce requires:
I'd try to add a complete sentence before a bulleted list:
eZ Commerce requires the following items before installation:
or even
Before you install eZ Commerce, make sure that you obtain the following items:

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +- An eZ Platform Version 2.5.x installation (see [Requirements](https://doc.ezplatform.com/en/2.5/getting_started/requirements_and_system_configuration/)).
Is "eZ Platform Version 2.5.x" a proprietary name? If not, I'd go along "eZ Platform in version 2.5.x"
However, when I search the resources (both docs and github), I see variations of the name: eZ Platform v2.5, eZ Platform 2.5, but not "version 2.5". Do we have a naming convention for product versions?

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
>      Recommended PHP Version: 7.2
I would move this piece of intormation to the parent bullet:
An eZ Platform Version 2.5.x installation with PHP in version 7.2. For details, see [Requirements](https://doc.ezplatform.com/en/2.5/getting_started/requirements_and_system_configuration/).

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +- To use ERP connection: an ERP system supported by eZ Commerce and the Web-Connector
I'm thinking whether optional requirements could be spelled out:
Optional: To use the ERP connection, an ERP system supported by eZ Commerce and the Web-Connector are required. For a list of suported ERP systems, see...
Also - is it web connector, webconnector, or Web-Connector? See my other comment above.

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +## Client
Could we have "Client installation requirements" header, "eZ Commerce installation requirements" header above, and "Server installation requirements" below? Would it make sense?

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +|Browsers|Depends on the design used for the project.</br>The standard eZ Commerce supports:</br>Internet Explorer 9,10,11 (IE8 should work as well)</br>All the other modern browsers like Chrome, Fir
"The standard eZ Commerce supports:" -> "A standard eZ Commerce installation supports the following browsers:"
Do we want to leave "IE8 should work"? If it works 100%, let's list it, if not, I'd remove it.
"All the other modern browsers like Chrome, Firefox, Safari, Opera" -> "Other modern browsers, for example, Chrome, Firefox, Safari, and Opera."

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +eZ Commerce requires a dedicated server. Due to security reasons shared hosting is not recommended.
"Due to security reasons shared ..." -> "Due to security reasons, shared ..."

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +    Don't store session as a file on the file system. This might cause locking problems.
This statement calls for a caution, not a note. 
"Do not store session information as a file on the file system."

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
>      Details see [Session handling](../guide/configuration/session_handling.md)
For details, see ...

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +Check if your webserver configuration (or Varnish) blocks cookies which are not used in the application.
"webserver" -> "web server"
"cookies which" -> "cookies that"

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/installation_and_configuration_faqs.md
> +## What configuration is required in order to communicate with ERP?
"in order" is redundant throughout

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/installation_and_configuration_faqs.md
>  In order to communicate with ERP you have to make sure, that:
To communicate with the ERP system, make sure that:

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +The reason is that additional cookies might influence the caching behavior in the backend. Some parts of the site are cached per session (e.g. the basket preview). It uses an ESI block which uses a c
"The reason is that " is obsolete.
"e.g." - I would consider using "for example" throughout the docs, as it is recommended to spell out abbreviations.
"It" - what is meant by "it" in the sentence - the session, the site?

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +For nginx in your vhost configuration:
Should there be a comma after "nginx"?

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +In addition to the requirements for eZ Platform the following software needs to be installed:
Should there be a comma after "Platform"?

2020-05-11 08:29 UTC, dabrt commented on docs/getting_started/requirements.md
> +If you encounter issues in the backend with missing chart data in the cockpit please check this setting and restart mysqld.
Should there be a comma after "cockpit"?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +eZ Commerce provides a flexible basket system. A basket is identified by:
I would consider avoiding passive voice, hence:
The following parameters identify a basket:

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +The basket can have one of the following types:
Can you have a type?
I would consider writing: "The basket can be of one of the following types:"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +A standard basket (type `basket`) may use different states during the checkout process. After the order has been sent, the basket will get the special state `ordered`.
"may use" -> "can be in"
"will get the special state `ordered`" -> "is assigned the state `ordered`" (If it is it really special, like it does not happen a lot, than "special" could stay, followed by a detailed explanation. Otherwise, I'd remove "special".)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +- Basket Parties
Basket parties (capitalization)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +Additional fields can be placed in the basket header (`dataMap` Field).
"Additional fields can be placed"
Who places the fields in the header? Is it the system or the reader? Either way, I'd try to avoid the passive voice and go along the lines of:
"You can place additional fields..." (or "The system can place....")

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +Basket lines contains info such as:
contains -> contain?
info -> information (to avoid jargon)
"info such as" -> "the following information"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +For each shop a `shop_id` can be configured. The `shop_id` will be stored in the basket.
To avoid the passive voice,, I'd go along the lines of:
You can configure a `shop_id` for each shop. The basket stores the `shop_id` value.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +Additional costs can be stored in the basket to implement all kinds of additional costs or discounts, such as:
Similarly:
"The basket can store additional costs..."
Is "such as" used as "for example" here? If so, I'd consider using "for example"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +Configuration controls which Fields from the product are stored.
Why are "Fields" capitalized?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +The basket contains a flag which controls if a recalculation has to be done (timeout).
"a flag which " -> "a flag that"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +After a login eZ Commerce merges the products from the existing basket (filled as an anonymous user) and a basket which is already stored for the given user id of the user.
"After a login eZ Commerce..." - Who performs the login? Is it the user who logs into the store? I would write specifically, for example "After the user logs in, eZ Commerce..."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +A basket can be shared if a user logs in in different browsers (default) or bound to session only.
"from different browsers (default), or bound to session only"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket.md
> +In case a basket shall be not shared in case the same user logs in twice a setting can be adapted (default: `false`)
I would consider removing the repeated "in case" phrase and using a simplier language (for non-English people):
If you do not want the basket to be shared when the same user logs in with several sessions, toggle the following setting (by default it is `false`):

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_data_model.md
>  - a basket header containing the header information such as id's, info about the invoice party and delivery
containing - that contains

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_data_model.md
> +- 1..n basket lines containing information about the products
containing - that contains

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_data_model.md
> +    Also check [Doctrine Datatypes](../../../cookbook/doctrine_mapping_datatypes.md).
I am wondering if a note can be the first element of a paragraph. If it is a note, could we place it at the end of the paragraph (that otherwise contains a list of fields)?

Also, I would expand the "Also check" to "For more information about...., see..." to give readers a reason to follow the link.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_data_model.md
> +|basketId|Primary key. ID must be an integer since it will be passed to the ERP as well as in order to ensure that one order is placed just once. Some ERP systems accept just integer ID because of th
Primary key, must be an integer, because IDs are passed to the ERP system. Some ERP systems accept integer IDs only to ensure that one order is placed just once.|int|Yes|

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_data_model.md
> +|guid|ID which identifies the order uniquely across all Systems (e.g. ERP, Shop and Payment System)|string||
which-> that
Or even better - "Uniquely identifies the order..."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_data_model.md
> +|erpFailCounter|Used in the `processFailedOrder()` method of the `BasketService` in order to count the number of tries (of submitting the order to the ERP)|int||
tries -> attempts

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_data_model.md
> +|isIncVat|Is the price inc. VAT|boolean||
Is the price inc. VAT -> Does the price incl. VAT

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_data_model.md
> +|remark|An additional remark of the user|string||
Inconsistency - Several strings begin with an article, other do not. Consistent would be better

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_data_model.md
>  !!! note
If the note is the only content in the paragraph, save for the table, why not remove the "note" formatting?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_data_model.md
> +|getBasketBySessionId|Get basket by SessionId|$sessionId, $state, $type, $name = null, $splittingcode = null|
My guess is that it should be "Gets...". Same applies to the next line.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_events/basket_eventlistener_in_the_standard.md
> +The allowed quantity is stored in `catalogElement` as a regex - `$allowedQuantity` - and is evaluated by a `preg_match()` function.
could it be "in the `catalogElement` object"? (repeated)
"a `preg_match()` function" -> "the `preg_match()` function"?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_events/basket_eventlistener_in_the_standard.md
> +The packaging unit is stored in `catalogElement` as `packagingUnit`. If the requested quantity does not correspondent the packaging unit, the quantity is increased to the next possible quantity that
"does not correspondent the packaging unit" -> "does not correspond to the packaging unit"
"quantity that will corresponding the packaging unit." -> "quantity that corresponds to the packaging unit."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_events/basket_eventlistener_in_the_standard.md
> +    #here you can enable/disable the DiscontinuedProductsListener
`DiscontinuedProductsListener`
(formatting)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_events/basket_eventlistener_in_the_standard.md
> +There are three possibilities when listener checks stock information:
a listener

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_events/basket_events.md
> +- check if the minimum quantity has to be checked: You will find an example in the document [Product quantity validation](../../basket_features/product_quantity_validation.md)
"checked: You will find an example in the document..." -> "checked. For an example, see..."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_events/basket_events.md
> +To take advantage from the existing events to e.g. modify some Basket or BasketLine data, your `EventService` must listen to these Events (Events IDs see above):
"events to e.g. modify some Basket or BasketLine data" -> "events, for example, to modify some Basket or BasketLine data"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_events/basket_events.md
> +You also have to implement appropriate methods in your `EventService`:
I would suggest going along the lines of:
"You must also implement..."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_routing.md
> +| /basket/show   | showAction()   | silversolutions_basket_show    | shows basket with all basket lines                                            |
"a basket"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basket_routing.md
> +| basket    | Basket | optional. This parameter cannot be provided as a POST parameter. It's used internally |
"It's used internally" -> "For internal use only" sounds more formal

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basketservice.md
> +|getBasket|Returns basket of current user with state `new`|Request $request</br>string $state|Basket|
a basket ot the current user

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basketservice.md
> +|storeBasket|Stores basket in the database. If necessary, the Price engine is initiated and Prices for Totals are calculated and stored.</br>Also the flag `$allProductsAvailable` is set here. If requ
a basket
Also,
If required,

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basketservice.md
> +|getBasketGroupList|Get a list of used codes - `GroupCalcList` or `GroupOrderList` depending on `groupType`</br>This function isn't implemented yet.|Basket $basket, $groupType|array - list of used co
Gets
isn't -> is not

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basketservice.md
> +|mergeBasket|Merges 2 baskets</br>the lines of the additionalBasket are assigned to the baseBasket|Basket $baseBasket, Basket $additionalBasket|Basket - merged basket|
Should `additionalBasket` and `baseBasket` be formatted as code?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basketservice.md
> +|copyBasket|Creates a new basket - with the state 'offered' - based on the given basket. All attributes will be copied.</br>The new basket will not be stored in the DB.|Basket $originBasket|Basket -
will -> are
will not -> are not

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basketservice.md
> +|removeBasket|Removes basket from the DB. If $withAssigned is true, all baskets that are based on this basket are removed from the DB.|Basket $basket, $withAssigned = false||
Should `$withAssigned` be formatted as code, or variables do not get the format?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basketservice.md
> +|getBasketBySessionId|Gets a basket from the DB by sessionId. If not found new Basket  is returned- but not stored in DB.|$sessionId, $type, $state, $name = null, $splittingCode = null|Basket - found
If not found, a new basket is returned -

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basketservice.md
> +|addBasketLineToBasket|Adds BasketLine to the Basket and stores the Basket in the DB. Is used for throwing and intercepting events.|Basket $basket, $sku, $quantity, $variantCode = null||
basket (lowercase)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_api/basketservice.md
> +|updateBasketLineInBasket|Updates a BasketLine in Basket. Is used for throwing and intercepting events. Basket is not stored in DB.|Basket $basket, BasketLine $basketLine, $increase = false||
basket (lowercase)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/additional_data_in_the_basket_line.md
> +To set a different value for the parameter there are two possibilities.
German syntax probably. I would suggest rewriting the sentence:
```suggestion
You can set a different value for the parameter by using the following two methods: 
```

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/additional_data_in_the_basket_line.md
> +To add some additional information to the basket line **only the template** will be modified. No other changes are necessary.
Does this mean the following?
To add more information to the basket line, you modify **the template only**.
I found it difficult to grasp the meaning of the sentence

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/basket_messages.md
> +Basket messages are stored in the Basket object, but they will not be stored in the database.
will not -> are not (repeated throughout the doc)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/basket_messages.md
>  |setSuccessMessage()|set one success message to the basket|$success|
Sets

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/basket_messages.md
> +|getSuccessMessages()|get all success messages from the basket. If it is not set, an empty string will be returned.||
Capitalization of the initial verb. Also, "Gets", "Sets" or "Deletes" (repeated)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/basket_messages.md
> +The messages parsed to the template through the `BasketController`, e.g. basket show:
What does "e.g. basket show" mean?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/basket_storage_time.md
> +The time basket is stored depends on whether a basket belongs to an anonymous user or a user logged in.
I would go along the lines of:
"The time for which a basket is stored depends on whether the basket..."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/basket_storage_time.md
> +A basket for a logged-in customer is stored for ever.
forever

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/basket_storage_time.md
> +You can use the `silversolutions:baskets:clear` command to clean up anonymous baskets which have been expired:
...to delete anonymous baskets that have expired:

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/calculating_prices.md
> +|Price|Price for one piece. This price may be calculated if the ERP doesn't provide a price for one piece. This is the normal case since due to complex price rules an ERP might not be able to give a
does not
This is normal, because due to complex price rules, ...

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/calculating_prices.md
> +- `remoteDataMap['stockNumeric']` - number of items in stock
Number
Boolean
(capitalization)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/discontinued_products.md
> +A listener can check if a product is not sold anymore (discontinued) and the user might have to be informed that this product is not available any more. This feature can be disabled (`discontinued_pr
"and the user might have to be informed that this product is not available any more." -> "so that the user is informed that the product is not available"?
"This feature can be disabled (`discontinued_products_listener_active`)." -> how? Would it be:
"This feature can be disabled by toggling the `discontinued_products_listener_active` setting."?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/discontinued_products.md
> +The listener will check if the current stock is equal or greater than the quantity the customer wants to order. In this case the order will be allowed. The optional config setting `discontinued_produ
I would definitely suggest using present tense.
'might enable"-> under what circumstances? -> "enables"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/product_quantity_validation.md
> +There is a help function `validateQuantity()` that checks if the given quantity (string - because it comes from a form) corresponds to the rules. (e.g. for 'float' quantity also comma is allowed). If
A helper function `validateQuantity()` checks ... (I would suggest using simplistic language in tech doc)
(string -> (expressed as a string
(e.g. for 'float' quantity also comma is allowed) - is this information relevant in this place, or do we expect users to know the difference between string, Boolean, float, integer, and so forth?
Or... am I reading it wrong at all and it means that the helper function validates values and allows values that contain commas? In such case, I would go along the lines of:
For example, when validating the value, the helper function allows values that contain commas, because commas are used in float values.
"If it does" - I suggest to avoid the use of "it", to avoid ambiguity.
"If the value is valid (or... corresponds to the rules), the helper function converts the quantity into a valid float value."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/product_quantity_validation.md
> +If it doesn't, the quantity is just returned, but not changed - it will be validated in `StandardBasketListener`.
Same here, I would suggest avoiding "it":
"If the value is invalid (or... does not conform to the rules), the helper function returns the string without conversion. Then the `StandardBasketListener` function validates the value again.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/product_quantity_validation.md
> +- `addAction()` - after the quantity is validated, the `addAction` checks, if it is 0. Than it is changed to 1.
I would capitalize the initial words, for consistency with other places.
Does the last sentence mean that "If so, the value is changed to 1."?
 
Also - how does the bulleted list connect to the paragraph above? I hava a hard time telling whether they are subfunctions of the StandardBasketListener, or separate validators, especially as the listener gets a separate header below.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/product_quantity_validation.md
> +- `updateAction()` - after the quantity is validated, the `addAction` checks, if it is 0. Than the `deleteAction()` is called and the product will be removed from basket.
1. In the sentence - is it "addAction" or "updateAction"?
2. I think I would remove the comma and write "the `addAction` (or `updateAction`, based on the answer above) checks if the value is 0."
2. Does the last sentence mean that "If so, the `deleteAction()` is called to remove the product from  the basket."?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/product_quantity_validation.md
> +- Checks if the given quantity is valid (e.g. negative numbers or strings are not allowed). If it is not valid, the action is not allowed (`STATUS_FAILED`).
(e.g. negative numbers or strings are not allowed) - are there any other checks? If there are, we'd need to list them here or redirect the reader to a full list. If not, I'd skip the "for example".

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/product_quantity_validation.md
> +- Checks if the given quantity is less than MIN. If so, it is set to MIN.
I am thinking whether "if" should not be avoide in phrases like the first sentence. "Checks whether", or "verifies whether". Having "whether" here we would help us avoid the repetition within the line.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/storing_parts_of_the_product_in_the_basket_line.md
> +This feature ensures that the basket always contains information about the product which should be ordered. If the customer is sending an order, the shop can ensure sure that all important product da
I am thinking whether the source actually means:
``` suggestion
This feature ensures that the basket always contains information about the products that are being ordered. When the customer sends an order, the shop is able to ensure that all important product data for the order is present, even if the product was meanwhile removed from the product catalog.
```

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/storing_parts_of_the_product_in_the_basket_line.md
> +#defines catalog element attributes that should be stored in a basket line
"should be" or just "are"?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/storing_parts_of_the_product_in_the_basket_line.md
> +    You can override this configuration, but make sure you have specified at least all required base attributes,
"specified all the required" - at least is redundant here

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/storing_parts_of_the_product_in_the_basket_line.md
> +    Also make sure that the attributes you have specified are either simple datatypes (int, float, boolean, string, array) or instances of [FieldInterface](../../../api/fields_for_ecommerce_data/fiel
"attributes that you specify"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/storing_parts_of_the_product_in_the_basket_line.md
> +To store the `CatalogElement` in the basket line the Doctrine listener is used. This listener uses the serialize service.
The basket line uses the Doctrine listener to store the `CatalogElement`.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_features/storing_parts_of_the_product_in_the_basket_line.md
> +This listener listens to different events to make sure that the catalog element is ALWAYS of type `CatalogElement` in the shop but `longtext` (serialized string) in the database.
Could it be:
"in the shop, and of `longtext` (serialized string) type in the database"?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_a_stored_basket_or_wishlist.md
> +This example shows how to offer a link which adds a product to the wishlist:
I would go along the lines of:
The following example shows how to offer a link that...

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_a_stored_basket_or_wishlist.md
> +This example opens a modal window providing the option to add a product to an existing stored basket or a new one:
Again, I suggest to write:
The following example opens a modal window that provides...

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +|ses_basket[0][sku]|YES||The SKU to be ordered. There has to be a valid `CatalogElement` for the given SKU.|
As a matter of preference, I would write:
A valid `CatalogElement` must exist for the given SKU.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +|ses_basket[0][updateNotPermitted]||1|Can be optionally passed, if you want to avoid, that the line with given SKU will be updated.</br>If set, a new basket line will be created every time when user
Could it be:
"Passed optionally, if you want to avoid updating the line with the given SKU."
?
"a new basket line is be created"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +Please note that the form tag which is used for the basket box only has to be moved to the product.twig.html template.
"Please note that " redundant. If it is a note, we can use note format. Otherwise, we can strip the decoration.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +In addition `<div class="js_add_to_basket_parent">` has to be added in order to tell JavaScript to collect this data as well.
I'd go along the lines of:
Also, `<div class="js_add_to_basket_parent">` must be added to tell JavaScript to collect this data as well.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +    - The key (here `remark`) must be a string and follow the rules for tag names since the key is converted to a tag later on when a price request is performed
I suggest to use ", because" instead of "since". Also, I'd remove "later on"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +Simple example using a standard POST form:
using -> that uses

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +    If you want to add more products to the basket (e.g. from wishlist), you need one form around all lines that will add all lines to the basket at once, but you might also need to add only one sing
"from the wishlist"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +    To add single product to the basket, you need to define parent elements with the class `.js-product-line`.
"a single"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +Example using Ajax:
I'd remove the line completely, it simply repeats what the header says already.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/basket/basket_ui/basket_ui.md
> +The controller provides a variable basket containing the content of the current basket.
containing -> that contains

2020-05-11 08:29 UTC, dabrt commented on docs/guide/bestseller/bestseller.md
> +Bestsellers can be displayed on Landing Pages, category pages and bestseller page.
Does "bestseller page" need an article?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/bestseller/bestseller.md
> +To enable bestsellers in the shop set the following parameter to true:
"shop, set"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/bestseller/bestseller.md
> +Inthe Back Office, go to eZ Commerce->Configuration Settings->Miscellaneous
In the (space missing)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/bestseller/bestseller_api.md
> +Fetches bestsellers from Solr
Fullstop missing

2020-05-11 08:29 UTC, dabrt commented on docs/guide/bestseller/bestseller_api.md
> +Adds an additional Solr field with the sum of basket lines
Fullstop missing
"with a sum"?
(Repeated in the lines above and below)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/bestseller/bestseller_cookbook.md
> +Edit the added block by clicking on the gear and select either a category of eZ products or add the Category code of an eContent category:
```suggestion
Edit the added block: click the gear, then either select a category of eZ products or add the Category code of an eContent category:
```

2020-05-11 08:29 UTC, dabrt commented on docs/guide/bestseller/bestseller_faq.md
> +Existing basket lines from confirmed baskets are counted for each bought product.
Could it be the following?
`BasketLineSumDeterminationService` counts existing basket lines from the confirmed baskets for each product that was purchased.
If so, the next sentence can be removed

2020-05-11 08:29 UTC, dabrt commented on docs/guide/bestseller/bestseller_faq.md
> +The `EzBestsellerIndexerPlugin` adds a Solr field with the sum of lines of a product.
Remove the initial The.
(We might have to review the docs again to standarize the way plugin, function, field and variable names are treated.
Either, for all the names, we add an article before and a description after, or we remove all instances of articles and descriptions from before and after all instances of formatted code element names.)

2020-05-11 08:29 UTC, dabrt commented on docs/guide/bestseller/bestseller_ui.md
> +- `EshopBundle/Resources/views/Bestsellers/bestsellers_box.html.twig` renders a slider for an `st_module` (100% or 50%)
It is either "an `st_module` module", or "`st_module`".
We need to figure this out.
Also, all three sentences need a fullstop.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs.md
> +In every part of the shop there is at least one generator responsible for creating breadcrumbs.
I'd write:
"generator that is responsible"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs.md
> +Breadcrumbs are generated using a general template called from `pagelayout.html.twig`.
I'd write:
"template that is called"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs.md
> +It uses [schema.org markup](http://schema.org/BreadcrumbList) for generating the HTML tags.
What is meant by "It" here?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs.md
> +- configuration for content Fields that should be used as breadcrumb labels
Should "Fields" be capitalized? I think I have asked this question before.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs.md
> +You can configure the Fields that should be used as labels for breadcrumb nodes.
should -> are or must?
My guess is that the author actually meant:
``` suggestion
You configure the fields that the breadcrumb support system uses as labels for breadcrumb nodes.
```

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/breadcrumbs_api.md
> +`Silversolutions/Bundle/EshopBundle/Resources/views/pagelayout.html.twig` defines a block named `breadcrumb` in which the breadcrumbs are rendered as a sub-controller call.
"... a block that is named `breadcrumb`, in which the breadcrumbs are rendered as a sub-controller call."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/breadcrumbs_api.md
> +The main gateway is a class `BreadcrumbsAggregateGenerator`. It collects all generators which can generate breadcrumbs.
"... the `BreadcrumbsAggregateGenerator` class, which collects all generators that can generate breadcrumbs."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/breadcrumbs_api.md
> +|`public function canRenderBreadcrumbs(Request $request);`|Verifies if the generator should render breadcrumbs for current request.|
"the current"

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/catalogbreadcrumbsgenerator.md
> +Checks if the `url` attribute is set in the request by the `StandardRouter`. If so, the catalog element matching the request and breadcrumb can be rendered.
"...that matches..."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/ezcontentbreadcrumbsgenerator.md
> +the breadcrumbs for standard eZ Platform content.
Is "renders" missing here?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/ezcontentbreadcrumbsgenerator.md
> +The generator triggers if the session attribute `location` is set. This is set by an eZ routine in the case the router matched a Content item.
Could it be the following?
An eZ routine sets the `location` attibute when the router matches a Content item.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +is for requests after a silver.module, which process the controller of the previous silver.module.
"is for" -> "handles"?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +**Example**: A silver.module Content item specifies the controller `SisoCustomerCenterBundle:Form:form` in order to display a form. After this form is submitted, it will not request the URL of the si
Specifies - does it mean "orders ... to do something" / "requests that ... does something"? 
Remove "in order"
", defined" -> "that is defined"
"nonetheless..." -> ", even though eZ Platform still displays breadcrumbs for the silver.module."?

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +This generator is responsible for this special case of requests. It listens to two kernel events in order to add some request attributes and save the last used silver.module ID temporarily in the ses
```suggestion
The generator handles such requests: It listens to two kernel events to add request attributes and temporarily save the ID of the last silver.module in the session.
```

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +In order to memorize a formerly displayed silver.module element, its ID is stored in the session and restored if the next page matches the controller, which is defined in the respective silver.module
Who/what momerizes the silver.module? I'd rewriite the sentence in active voice. Also, I'd break it in a series of shorter sentences. I would spell out the object hidden behind "It".

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +is the listener method the temporary storage of the silver.module ID in the session.
"...for the temporary..."

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/routesbreadcrumbsgenerator.md
> +generates the breadcrumbs for the Symfony routes.
Two paragraphs up the name of the method was preceded by a word "Method..." For the sake of consistency I would choose either way, my suggestion is to follow this example, meaning to make the sentence begin with the name of the method only.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +Method `Silversolutions\Bundle\EshopBundle\Service\Breadcrumbs\PostSilverModuleBreadcrumbsGenerator::onKernelRequest()`
See comment below

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/routesbreadcrumbsgenerator.md
> +If the `eZ\Publish\Core\MVC\Symfony\Routing\ChainRouter` matches the request, this generator is responsible.
The before the name of the router seems obsolete.

2020-05-11 08:29 UTC, dabrt commented on docs/guide/breadcrumbs/breadcrumbs_api/routesbreadcrumbsgenerator.md
> +This gnerator renders breadcrumbs if the route for the currently matched controller action
"genrator"->"generator"

2020-05-12 08:13 UTC, MagdalenaZuba requested changes

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/api/rest_api.md
> +eZ Commerce extends the Rest API of eZ Platform with:
```suggestion
eZ Commerce extends the REST API of eZ Platform with the following features:
```
REST as it is abbreviation of Representational state transfer

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/cookbook/frontend_customizing/4_front_end_stack_in_details/4.2_customized_foundation_framework/4.2._customized_foundation_framework.md
> +If you need some features from the higher eZ Commerce version, you will need to create the templates by yourself.
```suggestion
If you need features from the newer version of eZ Commerce, you must create the templates by yourself.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/getting_started/installation.md
> +Make sure that you have setup proper auth parameters for the updates.ez.no update server. You will receive the login parameters from the customer portal at ez.no:
```suggestion
Make sure to configure proper authentication parameters for the updates.ez.no update server. You will receive the login parameters from the customer portal at <https://www.ibexa.co/>:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/getting_started/installation_and_configuration_faqs.md
> +## What configuration is required in order to communicate with ERP?
```suggestion
## What configuration is required to communicate with ERP?
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/getting_started/installation_and_configuration_faqs.md
> +You need to generate a secret using `./vendor/defuse/php-encryption/bin/generate-defuse-key`
```suggestion
Generate a secret using `./vendor/defuse/php-encryption/bin/generate-defuse-key` and
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/getting_started/installation_and_configuration_faqs.md
> +You can configure it in `parameters.yml`:
```suggestion
configure it in `parameters.yml`:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/getting_started/requirements.md
> +- An eZ Platform Version 2.5.x installation (see [Requirements](https://doc.ezplatform.com/en/2.5/getting_started/requirements_and_system_configuration/)).
```suggestion
- An eZ Platform v2.5.x installation (see [Requirements](https://doc.ezplatform.com/en/2.5/getting_started/requirements_and_system_configuration/)).
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/getting_started/requirements.md
> +- To use ERP connection: an ERP system supported by eZ Commerce and the Web-Connector
```suggestion
- To use ERP connection: an ERP system supported by eZ Commerce and the Web Connector 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/getting_started/requirements.md
> +|Browsers|Depends on the design used for the project.</br>The standard eZ Commerce supports:</br>Internet Explorer 9,10,11 (IE8 should work as well)</br>All the other modern browsers like Chrome, Fir
```suggestion
|Browsers|Depends on the design used for the project.</br>Internet Explorer 9, 10, 11</br>Chrome, Firefox, Safari, Opera|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/getting_started/requirements.md
> +Check if your webserver configuration (or Varnish) blocks cookies which are not used in the application.
```suggestion
Check if your web server configuration (or Varnish) blocks unused cookies. 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/getting_started/requirements.md
> +The reason is that additional cookies might influence the caching behavior in the backend. Some parts of the site are cached per session (e.g. the basket preview). It uses an ESI block which uses a c
```suggestion
The reason is that additional cookies might influence the caching behavior in the backend. Some parts of the site are cached per session (e.g. the basket preview). The site uses an ESI block which uses a Cache by Cookie.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/getting_started/requirements.md
> +For nginx in your vhost configuration:
```suggestion
For NGINX, in your vhost configuration:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket.md
> +Basket lines contains info such as:
```suggestion
Basket lines contain information such as:
```
As we are not sure if the following information is complete, it is better to avoid making it seem so.

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket.md
> +After a login eZ Commerce merges the products from the existing basket (filled as an anonymous user) and a basket which is already stored for the given user id of the user.
```suggestion
After the user logs in, eZ Commerce merges the products from the existing basket (filled as an anonymous user) and a basket which is already stored for the given user ID.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket.md
> +If an SKU is already present in a basket, a new line is created in the basket of the user.
```suggestion
If an SKU is already present in a basket, a new line is created in the user's basket.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket.md
> +A basket can be shared if a user logs in in different browsers (default) or bound to session only.
```suggestion
A basket can be shared if a user logs in from a different browsers (default), or it can be bound to the session.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket.md
> +In case a basket shall be not shared in case the same user logs in twice a setting can be adapted (default: `false`)
```suggestion
If you do not want the basket to be shared between different sessions, change the following setting to `true`:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
>  - a basket header containing the header information such as id's, info about the invoice party and delivery
```suggestion
- a basket header that contains information such as ID's, the invoice party and delivery
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +- 1..n basket lines containing information about the products
```suggestion
- 1..n basket lines that contain information about the products 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
>  # Basket
```suggestion
## Basket
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|basketId|Primary key. ID must be an integer since it will be passed to the ERP as well as in order to ensure that one order is placed just once. Some ERP systems accept just integer ID because of th
```suggestion
|basketId|Primary key, must be an integer, because IDs are passed to the ERP system.|int|Yes|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|originId|Relation to the `originBasket`, primary key of the `originBasket` - if the basket is a copy of another basket with state 'new'|int||
```suggestion
|originId|Relation to the `originBasket`, primary key of the `originBasket` - if the basket is a copy of another basket with state `new`|int||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|guid|ID which identifies the order uniquely across all Systems (e.g. ERP, Shop and Payment System)|string||
```suggestion
|guid|Unique ID which identifies the order across all Systems (e.g. ERP, Shop and Payment System)|string||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|basketName|The basket name given by user for function `storedBasket`. In this case the attribute `type` is `storedBasket` (see [Wishlist and stored baskets](../../wishlist_and_stored_baskets/wishlis
```suggestion
|basketName|The basket name given by a user to function `storedBasket`. In this case the attribute `type` is `storedBasket` (see [Wishlist and stored baskets](../../wishlist_and_stored_baskets/wishlist_and_stored_baskets.md))|string||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|invoiceParty|Invoice address. Note: in order process the address may have to be updated if the customer changes the invoice address meanwhile (see Customers)|Party||
```suggestion
|invoiceParty|Invoice address. Note: in order to process, the address may have to be updated if the customer changes the invoice address (see Customers)|Party||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|buyerParty|Customer address.  Note: in order process the address may have to be updated if the customer changes the invoice address meanwhile (see Customers)|Party||
```suggestion
|buyerParty|Customer address.  Note: in order to process, the address may have to be updated if the customer changes the invoice address(see Customers)|Party||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|dateLastModified|Datetime of the basket last modification|Datetime|Yes|
```suggestion
|dateLastModified|`datetime` of the basket last modification|Datetime|Yes|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|dateCreated|Datetime of the basket creation|Datetime|Yes|
```suggestion
|dateCreated|`datetime` of the basket creation|Datetime|Yes|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|shop|Code of the shop where the order has been placed. The code is defined in the silver.e-shop.yml|string||
```suggestion
|shop|Code of the shop where the order has been placed. The code is defined in the `silver.e-shop.yml`|string||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|totalsSum|Stores an array of basketTotals objects, used by order splitting|BasketTotals||
```suggestion
|totalsSum|Stores an array of `BasketTotals` objects, used by order splitting|BasketTotals||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|additionalLines|Array of `AdditionalLine` objects which can contain more information about products (eg. additional shipping costs, vouchers, another product for free, promotions)|array of Additiona
```suggestion
|additionalLines|Array of `AdditionalLine` objects which can contain more information about products (e.g. additional shipping costs, vouchers, another product for free, promotions)|array of AdditionalLine||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|allProductsAvailable|True if all products in basket are available. Please not that this value can be checked only if a service such as the ERP provides Stockinfo. The logic is:</br>initially the val
```suggestion
|allProductsAvailable|True if all products in basket are available. Please note that this value can be checked only if a service such as the ERP provides `StockInfo`. The logic is:</br>initially the value is set to `true`</br>all products are checked if if a stock information is available it is checked: if stock is not available `allProductsAvailable` will be set to `false`</br>If no `StockInfo` is provided at all the (e.g. there was no ERP request) value might be wrong (true)|boolean||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|dataMap|Stores additional information (e.g. project specific attributes)</br>Defined and optional values in dataMap:</br>orderType - will be displayed in the order list in the backend|array||
```suggestion
|dataMap|Stores additional information (e.g. project specific attributes)</br>Defined and optional values in `dataMap:`</br>`orderType` will be displayed as order list in the backend|array||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
>  # BasketLine
```suggestion
## BasketLine
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|productType|E.g. product, event, subscription, ebook, download.</br>This field is used e.g. in order to</br>choose a template for displaying the product</br>info for price engine: which request  sha
```suggestion
|productType| Type of product e.g. product, event, subscription, ebook, download.</br>This field is used e.g. in order to</br>choose a template for displaying the product</br>info for price engine (which request should be sent to the ERP)</br>Example: `OrderableProductNode`|string|Yes|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|remark|An additional remark of the user|string||
```suggestion
|remark|Additional remark from the user|string||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|remoteDataMap|Additional information for the given basket line. This field may contain extra data provided by the user for this basket line (e.g. a special field such as a length or a reference to a
```suggestion
|remoteDataMap|Additional information for the given basket line. This field may contain extra data provided by the user for this basket line (e.g. a special field such as a length or a reference to an internal order number).</br>The price engine will set the following attributes in the `remoteDataMap` when provided by the price service (e.g. by an ERP system):</br>`stockNumeric` - number of items in stock</br>`onStock` - boolean|array||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +    BasketTotals is not an Entity, therefore it has no table in the database. BasketTotals is stored in Basket as:
```suggestion
    `BasketTotals` is not an Entity, therefore it has no table in the database. `BasketTotals` is stored in the Basket as:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|getBasketBySessionId|Get basket by SessionId|$sessionId, $state, $type, $name = null, $splittingcode = null|
```suggestion
|getBasketBySessionId|Gets basket by `SessionId`|$sessionId, $state, $type, $name = null, $splittingcode = null|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_data_model.md
> +|getBasketByUserId|Get basket by userId|$userId, $state, $type, $name = null, $splittingcode = null|
```suggestion
|getBasketByUserId|Gets basket by `userId`|$userId, $state, $type, $name = null, $splittingcode = null|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_events/basket_eventlistener_in_the_standard.md
> +The MIN and MAX values are stored in `EshopBundle/Resources/config/basket.yml` as a *default*, if not set in `catalogElement` as `$minOrderQuantity` and `$maxOrderQuantity`.
```suggestion
The min and max values are stored in `EshopBundle/Resources/config/basket.yml` as a *default*, if not set in `catalogElement` as `$minOrderQuantity` and `$maxOrderQuantity`.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_events/basket_eventlistener_in_the_standard.md
> +The packaging unit is stored in `catalogElement` as `packagingUnit`. If the requested quantity does not correspondent the packaging unit, the quantity is increased to the next possible quantity that
```suggestion
The packaging unit is stored in `catalogElement` as `packagingUnit`. If the requested quantity does not correspond to the packaging unit, the quantity is increased to the next possible quantity that corresponds to the packaging unit.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_events/basket_eventlistener_in_the_standard.md
> +    #here you can enable/disable the DiscontinuedProductsListener
This is a comment in the code, we do not format or change comments.

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basket_routing.md
> +| basket    | Basket | optional. This parameter cannot be provided as a POST parameter. It's used internally |
```suggestion
| basket    | Basket | Optional. This parameter cannot be provided as a POST parameter. It's used internally. |
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|getBasket|Returns basket of current user with state `new`|Request $request</br>string $state|Basket|
```suggestion
|getBasket|Returns basket of the current user with state `new`|Request $request</br>string $state|Basket|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|getBasketGroupList|Get a list of used codes - `GroupCalcList` or `GroupOrderList` depending on `groupType`</br>This function isn't implemented yet.|Basket $basket, $groupType|array - list of used co
```suggestion
|getBasketGroupList|Gets a list of used codes - `GroupCalcList` or `GroupOrderList` depending on `groupType`.</br>This function isn't implemented yet.|Basket $basket, $groupType|array - list of used codes|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|mergeBasket|Merges 2 baskets</br>the lines of the additionalBasket are assigned to the baseBasket|Basket $baseBasket, Basket $additionalBasket|Basket - merged basket|
```suggestion
|mergeBasket|Merges 2 baskets</br>the lines of the `additionalBasket` are assigned to the `baseBasket`|Basket $baseBasket, Basket $additionalBasket|Basket - merged basket|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|copyBasket|Creates a new basket - with the state 'offered' - based on the given basket. All attributes will be copied.</br>The new basket will not be stored in the DB.|Basket $originBasket|Basket -
```suggestion
|copyBasket|Creates a new basket - with the state `offered` - based on the given basket. All attributes are be copied.</br>The new basket are not be stored in the DB.|Basket $originBasket|Basket - copied basket|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|removeBasket|Removes basket from the DB. If $withAssigned is true, all baskets that are based on this basket are removed from the DB.|Basket $basket, $withAssigned = false||
```suggestion
|removeBasket|Removes basket from the database. If `$withAssigned` is true, all baskets that are based on this basket are removed from the database.|Basket $basket, $withAssigned = false||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|cleanUpBaskets|Removes all anonymous baskets from the storage that are older than given $datetime|\Datetime $datetime|int - count of the removed baskets</br>in failure null|
```suggestion
|cleanUpBaskets|Removes all anonymous baskets from the storage that are older than given `$datetime`|\Datetime $datetime|int - count of the removed baskets</br>in failure null|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|getBasketByUserId|Gets a basket from the DB by userId. If not found new Basket  is returned- but not stored in DB.|$userId, $type, $state, $name = null, $splittingCode = null|Basket - found or new b
```suggestion
|getBasketByUserId|Gets a basket from the database by `userId`. If not found, a new Basket  is returned but not stored in the database.|$userId, $type, $state, $name = null, $splittingCode = null|Basket - found or new basket|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|getBasketBySessionId|Gets a basket from the DB by sessionId. If not found new Basket  is returned- but not stored in DB.|$sessionId, $type, $state, $name = null, $splittingCode = null|Basket - found
```suggestion
|getBasketBySessionId|Gets a basket from the database by `sessionId`. If not found, a new Basket  is returned but not stored in the database.|$sessionId, $type, $state, $name = null, $splittingCode = null|Basket - found or new basket|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|addBasketLineToBasket|Adds BasketLine to the Basket and stores the Basket in the DB. Is used for throwing and intercepting events.|Basket $basket, $sku, $quantity, $variantCode = null||
```suggestion
|addBasketLineToBasket|Adds BasketLine to the Basket and stores the Basket in the database. Is used for throwing and intercepting events.|Basket $basket, $sku, $quantity, $variantCode = null||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|removeBasketLineFromBasket|Removes a BasketLine from a basket. Is used for throwing and intercepting events. Basket is not stored in DB.|Basket $basket, BasketLine $basketLine||
```suggestion
|removeBasketLineFromBasket|Removes a BasketLine from a Basket. Is used for throwing and intercepting events. Basket is not stored in the database.|Basket $basket, BasketLine $basketLine||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|updateBasketLineInBasket|Updates a BasketLine in Basket. Is used for throwing and intercepting events. Basket is not stored in DB.|Basket $basket, BasketLine $basketLine, $increase = false||
```suggestion
|updateBasketLineInBasket|Updates a BasketLine in Basket. Is used for throwing and intercepting events. Basket is not stored in the database.|Basket $basket, BasketLine $basketLine, $increase = false||
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_api/basketservice.md
> +|createBasketLineForSku|Creates a new BasketLine for the given sku and variantCode|Basket $basket, $sku, $quantity, $variantCode = null|BasketLine|
```suggestion
|createBasketLineForSku|Creates a new BasketLine for the given SKU and `variantCode`|Basket $basket, $sku, $quantity, $variantCode = null|BasketLine|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_faq.md
> +A dataMap can be used to store all kinds of information. It can be addressed by the PHP API or filled directly using a form:
```suggestion
A `dataMap` can be used to store all kinds of information. It can be addressed by the PHP API or filled directly using a form:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/additional_data_in_the_basket_line.md
> +To add some additional information to the basket line **only the template** will be modified. No other changes are necessary.
```suggestion
You can add additional information to the basket line ** by modifying the template**. No other changes are necessary.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/basket_messages.md
> +It is possible to store several success, error or notice messages for products.
```suggestion
It is possible to store several success, errors or notice messages for products.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/basket_messages.md
> +Basket messages are stored in the Basket object, but they will not be stored in the database.
```suggestion
Basket messages are stored in the Basket object, but they cannot be stored in the database.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/basket_storage_time.md
> +The time basket is stored depends on whether a basket belongs to an anonymous user or a user logged in.
```suggestion
The time for which a basket is stored depends on whether a basket belongs to an anonymous user or a logged user.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/basket_storage_time.md
> +A basket for a logged-in customer is stored for ever.
```suggestion
A basket for a logged user is stored forever.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/basket_storage_time.md
> +You can use the `silversolutions:baskets:clear` command to clean up anonymous baskets which have been expired:
```suggestion
You can use the `silversolutions:baskets:clear` command to remove expired anonymous baskets:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/calculating_prices.md
> +The basket recalculates the prices after each change of the basket. The price engine will be requested when the basket is stored. This avoids the price engine being triggered several times (e.g. if m
```suggestion
The basket recalculates the prices after each change of the basket. The request to the price engine will be sent when the basket is stored. This avoids the price engine being triggered several times (e.g. if more than one product has been updated or added). The prices provided by the price engine (and ERP) will be stored in the basket for each line.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/calculating_prices.md
> +|Price|Price for one piece. This price may be calculated if the ERP doesn't provide a price for one piece. This is the normal case since due to complex price rules an ERP might not be able to give a
```suggestion
|Price|Price for one piece. This price may be calculated if the ERP doesn't provide a price for one piece. This is standard approach due to complex price rules.|
```
Removed repeated information

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/calculating_prices.md
> +In addition the prices will be calculated each time the basket is changed.
```suggestion
In addition, the prices will be calculated each time the basket is changed.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/discontinued_products.md
> +A listener can check if a product is not sold anymore (discontinued) and the user might have to be informed that this product is not available any more. This feature can be disabled (`discontinued_pr
```suggestion
A listener can check if a product is not sold anymore (`discontinued`) so the user can be informed that this product is not available any more. This feature can be disabled (`discontinued_products_listener_active`).
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/product_quantity_validation.md
> +There is a help function `validateQuantity()` that checks if the given quantity (string - because it comes from a form) corresponds to the rules. (e.g. for 'float' quantity also comma is allowed). If
```suggestion
The help function `validateQuantity()` checks if the given quantity (string) corresponds to the rules set e.g. for float value. If the quantity matches, it is converted into a valid float value.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/product_quantity_validation.md
> +- Checks if the given quantity is more than MAX. If so, it is set to MAX.
```suggestion
- Checks if the given quantity is more than max or less than min. If so, it is set to either max or min.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/product_quantity_validation.md
> +- Checks if the given quantity is less than MIN. If so, it is set to MIN.
```suggestion  
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/storing_parts_of_the_product_in_the_basket_line.md
> +This feature ensures that the basket always contains information about the product which should be ordered. If the customer is sending an order, the shop can ensure sure that all important product da
```suggestion
This feature ensures that the basket always contains information about the product which should be ordered. When the customer sends an order, the shop can verify if all relevant product data for the order is present, even if the product was removed from the product catalog. 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/storing_parts_of_the_product_in_the_basket_line.md
> +#defines catalog element attributes that should be stored in a basket line
code comment

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_features/storing_parts_of_the_product_in_the_basket_line.md
> +    You can override this configuration, but make sure you have specified at least all required base attributes,
```suggestion
    You can override this configuration, but make sure that all required base attributes are specified,
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +To successfully add products to the basket you need to provide some mandatory parameters.
```suggestion
To successfully add products to the basket you need to provide mandatory parameters.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +|ses_basket[0][updateNotPermitted]||1|Can be optionally passed, if you want to avoid, that the line with given SKU will be updated.</br>If set, a new basket line will be created every time when user
```suggestion
|ses_basket[0][updateNotPermitted]||1|Can be passed optionally if you want to avoid updating the line with given SKU will.</br>If set, a new basket line will be created every time the user adds a product with the same SKU to the basket.|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +Please note that the form tag which is used for the basket box only has to be moved to the product.twig.html template.
```suggestion
Please note that the form tag which is used for the basket box has to be moved to the `product.twig.html` template.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +    - The key (here `remark`) must be a string and follow the rules for tag names since the key is converted to a tag later on when a price request is performed
```suggestion
    The key (here `remark`) must be in a string format and follow the rules for tag names because the key is converted to a tag during a price request.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
> +Simple example using a standard POST form:
```suggestion
Add to basket POST request:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/basket/basket_ui/adding_products_to_the_basket.md
>  You need to define one parent element with the class .js-add-to-basket-parent
```suggestion
You need to define one parent element with the class `.js-add-to-basket-parent`
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/bestseller/bestseller.md
> +Inthe Back Office, go to eZ Commerce->Configuration Settings->Miscellaneous
```suggestion
In the Back Office, go to eZ Commerce->Configuration Settings->Miscellaneous.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/bestseller/bestseller_api.md
> +Fetches bestsellers from Solr
```suggestion
Fetches bestsellers from Solr.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/bestseller/bestseller_api.md
> +Adds an additional Solr field with the sum of basket lines
```suggestion
Adds an additional Solr field with the sum of basket lines.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/bestseller/bestseller_api.md
> +Adds an additional Solr field with the sum of basket lines
```suggestion
Adds an additional Solr field with the sum of basket lines.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/bestseller/bestseller_ui.md
> +- `EshopBundle/Resources/views/Bestsellers/bestsellers_box_esi.html.twig` creates an Edge Side Includes tag and calls the controller for landing page bestsellers
```suggestion
- `EshopBundle/Resources/views/Bestsellers/bestsellers_box_esi.html.twig` creates an Edge Side Includes tag and calls the controller for Landing Page bestsellers
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs.md
> +It uses [schema.org markup](http://schema.org/BreadcrumbList) for generating the HTML tags.
```suggestion
The `BreadcrumbList` by [schema.org markup](http://schema.org/BreadcrumbList) is used for generating the HTML tags. 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/breadcrumbs_api.md
> +The main gateway is a class `BreadcrumbsAggregateGenerator`. It collects all generators which can generate breadcrumbs.
```suggestion
The main gateway is a `BreadcrumbsAggregateGenerator` class. It collects all generators that generate breadcrumbs. 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/breadcrumbs_api.md
> +The first generator that returns true from `canRenderBreadcrumbs()` wins and is used to render the breadcrumbs HTML code.
``` suggestion
The first generator that returns `true` from `canRenderBreadcrumbs()` is used to render the breadcrumbs HTML code.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/breadcrumbs_api.md
> +|`public function canRenderBreadcrumbs(Request $request);`|Verifies if the generator should render breadcrumbs for current request.|
```suggestion
|`public function canRenderBreadcrumbs(Request $request);`|Verifies if the generator should render breadcrumbs for the current request.|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/breadcrumbs_api.md
> +|[`PostSilverModuleBreadcrumbsGenerator`](postsilvermodulebreadcrumbsgenerator.md)|Renders breadcrumbs for a silver.module element|
```suggestion
|[`PostSilverModuleBreadcrumbsGenerator`](postsilvermodulebreadcrumbsgenerator.md)|Renders breadcrumbs for a `silver.module` element|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/ezcontentbreadcrumbsgenerator.md
> +the breadcrumbs for standard eZ Platform content.
```suggestion
renders the breadcrumbs for standard eZ Platform content.  
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +is for requests after a silver.module, which process the controller of the previous silver.module.
```suggestion
handles requests for a `silver.module`, which process the controller of the previous `silver.module`.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +    silver.modules themselves are standard Content items and their breadcrumbs are handled solely by the parent of this class which is [`EzContentBreadcrumbsGenerator`](ezcontentbreadcrumbsgenerator.
```suggestion
    silver.modules themselves are standard Content items and their breadcrumbs are handled solely by the parent of the [`EzContentBreadcrumbsGenerator` class](ezcontentbreadcrumbsgenerator.md).
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +Method `Silversolutions\Bundle\EshopBundle\Service\Breadcrumbs\PostSilverModuleBreadcrumbsGenerator::onKernelRequest()`
```suggestion
`Silversolutions\Bundle\EshopBundle\Service\Breadcrumbs\PostSilverModuleBreadcrumbsGenerator::onKernelRequest()` method
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +is the listener method for the preparation of the request for a post silver.module controller.
```suggestion
is the listener method that prepares the request for a post silver.module controller.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +Method `Silversolutions\Bundle\EshopBundle\Service\Breadcrumbs\PostSilverModuleBreadcrumbsGenerator::onKernelResponse()`
```suggestion
`Silversolutions\Bundle\EshopBundle\Service\Breadcrumbs\PostSilverModuleBreadcrumbsGenerator::onKernelResponse()` method
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/postsilvermodulebreadcrumbsgenerator.md
> +is the listener method the temporary storage of the silver.module ID in the session.
```suggestion
is the listener method that temporary stores the silver.module ID in the session.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/routesbreadcrumbsgenerator.md
> +If the `eZ\Publish\Core\MVC\Symfony\Routing\ChainRouter` matches the request, this generator is responsible.
```suggestion
If the `eZ\Publish\Core\MVC\Symfony\Routing\ChainRouter` matches the request, Routes Breadcrumbs Generator is responsible.

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/routesbreadcrumbsgenerator.md
> +Since this is the case for nearly every request, this generator must be registered with one of the lowest priorities.
```suggestion
Since this is the case for nearly every request, the generator must be registered with one of the lowest priorities.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_api/routesbreadcrumbsgenerator.md
> +This gnerator renders breadcrumbs if the route for the currently matched controller action
```suggestion
Routes Breadcrumbs Generator renders breadcrumbs if the route for the currently matched controller action
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_cookbook.md
> +To configure breadcrumbs for your custom route you need to add some configuration to this route.
```suggestion
To configure breadcrumbs for custom route you need to add additional configuration to this route.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_cookbook.md
> +This configures a custom route for the `BlogController::indexAction` action in your controller in `routing.yml`.
```suggestion
The above example shows how to configure a custom route for the `BlogController::indexAction` action in your controller in `routing.yml`.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_cookbook.md
> +In the example below when breadcrumbs are generated there will be two elements (Profile and Blog list)
```suggestion
In the example below when breadcrumbs are generated there will be two elements (Profile and Blog list):
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_cookbook.md
> +    There is a limitation when using this route generator. You can provide paths only if the corresponding action in the controller has no required parameters. There is no way of passing any paramete
```suggestion
    When using this route generator you can provide paths only if the corresponding action in the controller has no required parameters. There is no way of passing any parameters to the action.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_cookbook.md
> +### Write a generator class
```suggestion
### Create a generator class
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_cookbook.md
> +First, write a generator class.
```suggestion
First, create a generator class.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_cookbook.md
> +It needs to implement `BreadcrumbsGeneratorInterface` that only has two methods.
```suggestion
It needs to implement `BreadcrumbsGeneratorInterface` that has two methods.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_cookbook.md
> +Always create all the keys and leave the elements empty if not needed. Examples from some `BreadcrumbsGenerators`:
```suggestion
Always create all the keys and leave the elements empty if not needed. Examples from `BreadcrumbsGenerators`:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_faq.md
> +The `RoutesBreadcrumbsGenerator` need at least the parameter `breadcrumb_path`. This parameter usually contains the key of the current routing definition.
```suggestion
The `RoutesBreadcrumbsGenerator` needs the `breadcrumb_path` parameter. This parameter usually contains the key of the current routing definition.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_faq.md
> +- The `breadcrumb` block of the `pagelayout.html.twig` template was overridden by the currently displayed, extending template with empty content.
```suggestion
- The `breadcrumb` block of the `pagelayout.html.twig` template was overridden by the currently displayed one, extending template with empty content.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_faq.md
> +The parameter `content.tree_root.location_id` is used to limit the sub-shops to their subtrees (contains Location ID of the desired catalog).
```suggestion
The `content.tree_root.location_id` parameter is used to limit the sub-shops to their subtrees (contains Location ID of the desired catalog).
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_faq.md
> +This data can be used for example to define if a breadcrumb of a Location should be clickable or hidden.
```suggestion
This data can be used to define if a breadcrumb of a Location should be clickable or hidden.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/breadcrumbs/breadcrumbs_faq.md
> +The following example makes breadcrumbs bold and not clickable (if `crumb.translationParameters.type == 'catalog'`):
```suggestion
The following example changes the breadcrumbs to not clickable bold text (if `crumb.translationParameters.type == 'catalog'`):
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/caching_in_the_shop/basketpreview_cache_and_user_specific_data.md
> +Each service implementing the SessionDataInterface can return HTML fragments. The keys used should use the id of an container inside your site. eZ Commerce will replace this container automatically u
```suggestion
Each service implementing the `SessionDataInterface` can return HTML fragments. The keys should use the ID of a container inside your site. eZ Commerce will automatically replace this container by using the below HTML example.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/configuration/advanced_configuration.md
> +This configuration controls which countries will be offered in eZ Commerce (e.g. in registration forms or in the checkout)
```suggestion
This configuration controls which countries will be offered in eZ Commerce (e.g. in registration forms or in the checkout).
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/configuration/configuration.md
> +A parameter in `php.ini` (e.g. `/etc/php5/apache2/php.ini`) might have to be set up since it reduces the lifetime of a session:
```suggestion
A parameter in `php.ini` (e.g. `/etc/php5/apache2/php.ini`) should be set up since it reduces the lifetime of a session:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/configuration/configuration.md
> +The method `registerBundles()` in our kernel loads different bundles based on the environment.
```suggestion
The `registerBundles()` method in Kernel loads different bundles based on the environment.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/configuration/configuration.md
> +The value that is considered here comes is passed from the vhost configuration into the script.
```suggestion
The value that is considered here is passed from the vhost configuration into the script.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/configuration/configuration.md
> +If you want to set up special rules for shipping costs you can achieve this in the Back Office.
```suggestion
You can set up special rules for shipping costs in the Back Office.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/configuration/configuration.md
> +If you want to enable Paypal as a payment provider you need to configure:
```suggestion
If you want to enable PayPal as a payment provider you need to configure:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/configuration/session_handling.md
> +You need to create a session table in the DB if DB storage is used:
```suggestion
You need to create a session table in the database if database storage is used:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/configuration/session_handling.md
> +It is very important to set a session name. Otherwise eZ platform will generate a unique name per SiteAccess which causes issues if you switch e.g. the language/SiteAccess and users cannot share a ba
```suggestion
It is very important to set a session name. Otherwise eZ Platform will generate a unique name per SiteAccess which causes issues if you switch e.g. the language/SiteAccess and users cannot share a basket and login across SiteAccesses.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/configuration/setup_a_new_language.md
> +    If a new SiteAccess is introduced it is important to add a new policy for the anonymous user role:
```suggestion
    If a new SiteAccess is introduced it is important to add a new Policy for the anonymous user Role:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/configuration/setup_a_new_language.md
> +- ezpublish.siteaccess.groups.ezdemo_site_clean_group - Set new SiteAccess to general group "ezdemo_site_clean_group"
```suggestion
- ezpublish.siteaccess.groups.ezdemo_site_clean_group - Set new SiteAccess to general group `ezdemo_site_clean_group`
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/integrate_erp_systems/erp_communication/erp_components/erp_component_messages/erp_message_class_generator.md
> +ses: type classes would be stored into the eZ Commerce path and cust: type classes would be stored into the defined target directory. Also ses: type XML definition files are always read from the eZ C
```suggestion
- ses: type classes would be stored into the eZ Commerce path. XML definition files are always read from the eZ Commerce path.
- cust: type classes would be stored into the defined target directory. XML definition files are always read from the source path.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter2go/newsletter2go.md
> +|Short description|eZ Commerce provides an API to enable customers to register their e-mail addresses to a newsletter. This bundle integrates the newsletter service https://www.newsletter2go.de into
```suggestion
|Short description|eZ Commerce provides an API to enable customers to register their email addresses to a newsletter. This bundle integrates the newsletter service https://www.newsletter2go.de into the API.|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/price_engine/price_engine_api/price_engine_services/standardtemplatedebitorservice.md
> +This service makes usage of [StandardCountryZoneService](standardcountryzoneservice.md) to get the correct zone for the country. The country is determined from the given [BuyerParty.
```suggestion
This service makes usage of [StandardCountryZoneService](standardcountryzoneservice.md) to get the correct zone for the country. The country is determined from the given BuyerParty.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/addons_and_plugins.md
> +If a customer has a customer center all employees will be stored beneath the company folder. The shop administrator will have a good overview of the company and its related employees with a shop acco
```suggestion
If a customer has a customer center all employees are stored beneath the company folder. The shop administrator has an overview of the company and its related employees with a shop account. 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/addons_and_plugins.md
> +Discount or value vouchers can easily be created in the shop back end. A voucher contains discount conditions like minimum basket value or discountable products. Create individual vouchers that are v
```suggestion
Discount or value vouchers can easily be created in the shop backend. A voucher contains discount conditions like minimum basket value or discountable products. Create individual vouchers that are valid for a given number of uses, or for a set time period, or personalized vouchers that are only valid for one-time use.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +The catalog is built using categories and products. The categories and products can be translated.
```suggestion
The catalog is built using categories and products that can be translated. 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +Categories and products can be set up as Content items, or in eContent. eContent is a storage provider for eZ Commerce which can store product data in a very efficient way. It enables storing data (m
```suggestion
Categories and products can also be set up as Content items, or in eContent. eContent is a storage provider for eZ Commerce which can store product data in a very efficient way. It enables storing data (mostly for products and product groups) in database tables with a simple structure.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +Three different layouts are provided by default (displaying sub-categories, product list or both on the entry page of a category). You can also configure if bestsellers of the group should be display
```suggestion
Three different layouts are provided by default (displaying sub-categories, product list or both on the entry page of a category). You can also configure in the Back Office if bestsellers of the group should be displayed.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +A product type (not to be confused with variants) represents a collection of very similar products that differ only for some characteristics. It is used to show a list of products in a tabular way, e
```suggestion
A product type (not to be confused with variants) represents a collection of very similar products that differ only in some characteristics. It is used to show a list of products in a tabular way, every product can be added to the basket directly from overview page. 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +eZ Commerce supports variants with 1 or 2 levels.
```suggestion
eZ Commerce supports variants with one or two levels.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +The customer can change the order of the sorting by dragging and can decide to display only differences of the products.
```suggestion
The customer can change the order of the sorting by dragging and can display differences of the products.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +It respects the permissions and roles of the customer.
```suggestion
It respects the permissions and Roles of the customer.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +Almost all product fields can be used as a facet if they are indexed. This can be controlled by a configuration file which enables setting up different facets for the product catalog and search.
```suggestion
Almost all product Fields can be used as a facet if they are indexed. This can be controlled by a configuration file which enables setting up different facets for the product catalog and search.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +Facets can be grouped. For more complex facets new fields can be implemented using the IndexPlugin features of Solr search.
```suggestion
Facets can be grouped. For more complex facets new Fields can be implemented using the IndexPlugin features of Solr search.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +Note: There are restrictions for variants, it is not possible to mix the variant attributes as facets if the same attribute is set for main products.
```suggestion
!!! note

    There are restrictions for variants, it is not possible to mix the variant attributes as facets if the same attribute is set for main products.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/catalog_and_search.md
> +The autosuggest feature offers suggestion as you type and enables adding an orderable product to the basket directly from the search box. It suggests products, categories, downloads and content. The
```suggestion
The autosuggest feature offers suggestion as you type and enables adding an available product to the basket directly from the search box. It matches products, categories, downloads and content based on the name that starts with the search term.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/contact_forms_and_legal_aspects.md
> +eZ Commerce offers tools to set up a shop that is compliant with GDPR (General Data Protection Regulation)
```suggestion
eZ Commerce offers tools to set up shop that is compliant with GDPR (General Data Protection Regulation):
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/contact_forms_and_legal_aspects.md
> +- Cookie consent feature with a link to data privacy to inform the user about the cookies used
```suggestion
- Cookie consent feature with a link to data privacy to inform the user about used cookies 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/content_and_commerce.md
> +In the main navigation Product Catalog and Content items can be displayed. A partner can decide which Content Types should appear in the menu using configuration. The order of the navigation items ca
```suggestion
In the main navigation, Product Catalog and Content items can be displayed. A partner can configure which Content Types should appear in the menu. The order of the navigation items can be defined by the editor in the Back Office using the priority field.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/content_and_commerce.md
> +eZ Commerce adds 3 new blocks to the Page Builder:
```suggestion
eZ Commerce adds following new blocks to the Page Builder:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/content_and_commerce.md
> +    The Newsletter2Go Plugin  adds a Newsletter block to the Page Builder.
```suggestion
    The Newsletter2Go Plugin adds a Newsletter block to the Page Builder.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/content_and_commerce.md
> +If product data is stored in regular content, products or product slider can be embedded in all kinds of RichText Fields (e.g. in articles, news, blog posts and events).
```suggestion
If product data is stored in regular content, products or product slider can be embedded in the RichText Field (e.g. in articles, news, blog posts and events).
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/content_and_commerce.md
> +If products are stored in eContent and/or a PIM system, a product slider can be embedded in all RichText Field (e.g. in articles, news, blog posts and events) by using the element "Product card". Wit
```suggestion
If products are stored in eContent and/or a PIM system, a product slider can be embedded in the RichText Field (e.g. in articles, news, blog posts and events) by using the element "Product card". With eContent it is not possible to embed a single product.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/customer_registration.md
> +Existing customers - meaning customers that are set up in the connected ERP - can activate a shop account themselves by entering their customer number and one invoice number. The data is sent to the
```suggestion
Existing customers - meaning customers that are set up in the connected ERP - can activate a shop account themselves by entering their customer number and one invoice number. The data is sent to the ERP. If the data in ERP and the entered data match, the customer will get access to the shop immediately and a User Content item is set up automatically with the customer number from the ERP.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/customer_registration.md
> +A user can request a new password in case they have forgotten the existing one. Note: eZ Commerce does not use the eZ Platform "forgot password" feature.
```suggestion
A user can request a new password in case they have forgotten the existing one. eZ Commerce does not use the eZ Platform "forgot password" feature.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/ecommerce_administration.md
> +The configuration settings in the backend enable configuring the main behavior for the shop. In addition currency, payment and shipping options can be set per country (SiteAccess). The configuration
```suggestion
You configuring the main behavior of the shop in the configuration settings in the backend. In addition, you can set currency, payment and shipping options per country (SiteAccess). The configuration is stored using the version control features of the CMS. More advanced settings (e.g. VAT for different countries) can be set up in configuration files.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/erp_integration.md
> +|Login for B2B customer|The shop updates customer data from the ERP in realtime|The shop is using the customer data from the ERP. Always up-to-date.</br>The customer is always using the same data reg
```suggestion
|Login for B2B customer|The shop updates customer data from the ERP in a real-time|The shop is using the customer data from the ERP. Always up-to-date.</br>The customer is always using the same data regardless of the channel they are using.|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/erp_integration.md
> +|Realtime stock|The shop can request stock information in realtime.|The stock is updated in real time.|
```suggestion
|Realtime stock|The shop can request stock information in a real-time.|The stock is updated in real-time.|
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/erp_integration.md
> +- An order will be stored in the shop. A job will take care that the order is transmitted to the ERP when it is available again.
```suggestion
- An order will be stored in the shop. A job will transmit the order to the ERP when it is available again.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/erp_integration.md
>  ## Realtime stock information during checkout and in product detail page
```suggestion
## Real-time stock information during checkout and in product detail page
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/erp_integration.md
> +It enables analyzing the communication for a given time period. The view can be filtered by a time period and allows to identify the message which are performing good or not good.
```suggestion
It enables analyzing the communication for a given time period. The view can be filtered by a time period and allows to identify how messages are performing. 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/manage_products_prices_and_stock.md
> +A category contains a standard set of fields. A category is a Content Type and can be extended with additional Fields.
```suggestion
A category contains a standard set of Fields. A category is a Content Type and can be extended with additional Fields.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/manage_products_prices_and_stock.md
> +eZ Commerce offers a set of product Fields. Since a product is built using the flexible Content Type system it can be extended with new Fields easily.
```suggestion
eZ Commerce offers a set of product Fields. Since a product is built using the flexible Content Type system it can be easily extended with new Fields.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/manage_products_prices_and_stock.md
> +There are 3 preconfigured variant types: Color, Size, Color & Size
```suggestion
There are three preconfigured variant types: Color, Size, Color and Size
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/manage_products_prices_and_stock.md
> +The price management enables setting up prices manually. A price can be setup per SKU and SKU/variant. Each price can contain an offer price and a base price. If an offer price is set it will be disp
```suggestion
The price management enables setting up prices manually. A price can be setup per SKU and SKU/variant. Each price can contain an offer price and a base price. If an offer price is set it will be displayed in the shop as:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/manage_products_prices_and_stock.md
> +In addition prices can vary per customer group. There are 3 customer groups set up per default.
```suggestion
In addition, prices can vary per customer group. There are three customer groups set up per default. 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/manage_products_prices_and_stock.md
> +- if no price for a currency is set in a shop eZ Commerce offers 2 options, these can be set in the configuration per shop.
```suggestion
- if no price for a currency is set in a shop, eZ Commerce offers two options, these can be set in the configuration per shop.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/monitoring_and_control.md
> +All communication (request- and response messages), that is sent between shop and ERP system will be recorded and can bee seen here.
```suggestion
All communication (request and response messages), that is sent between shop and ERP system is recorded and can be reviewed.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/monitoring_and_control.md
> +In the tab email archive the shop owner/admin finds all e-mails which were automatically sent from the shop, with date of despatch, recipient, subject and status. He can see the mails and resend them
```suggestion
In the tab email archive the shop owner/admin can find all emails which were automatically sent from the shop, with date of dispatch, recipient, subject and status. They can check the emails and resend them if necessary.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/monitoring_and_control.md
> +If eContent is used as product data storage the shop owner can see all eContent types (product_group und product) with the associated attributes and where they are mapped.
```suggestion
If eContent is used as product data storage the shop owner can see all eContent types (`product_group` and `product`) with the associated attributes and where they are mapped.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/monitoring_and_control.md
> +In the tab "eContent types" he can see the eContent types with their associated attributes (product_group and product) and the mapping information.
```suggestion
In the tab "eContent types" they can see the eContent types with their associated attributes (`product_group` and `product`) and the mapping information.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/monitoring_and_control.md
>  In the "eContent tasks" he can see how many products and product groups there are in the shop. Furthermore the shop operator can create a new index, import a backup into the database and create a bac
```suggestion
In the "eContent tasks" they can see how many products and product groups there are in the shop. Furthermore the shop operator can create a new index, import a backup into the database and create a backup from the database.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/order_history.md
> +The documents for the chosen dates are fetched in real time.
```suggestion
The documents for the chosen dates are fetched in real-time.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/order_history.md
> +The user can choose which documents he wants to look for and decide for a period. If the ERP provides a tracking link this information will be displayed as well.
```suggestion
The user can choose which documents they want to look for and from what period. If the ERP provides a tracking link this information will be displayed as well. 
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/order_history.md
> +A customer can order the same products again easily:
```suggestion
A customer can easily order the same products again:
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/ordering_process.md
> +An upload function allows to upload a csv file containing a list of SKUs and quantities. Even more convenient is the drag and drop function.
```suggestion
An upload function allows to upload a CSV file containing a list of SKUs and quantities. Even more convenient is the drag and drop function.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/ordering_process.md
> +Step 1: A user can register as a new customer, existing customer or buy as a guest.
```suggestion
Step 1: A user can register an account, log in to an existing account or buy as a guest.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/ordering_process.md
> +Step 3: For delivery address the user can either choose the invoice address, one of the addresses from his address book or enter a new delivery address. Only the offered delivery addresses will be fe
```suggestion
Step 3: For delivery address the user can either choose the invoice address, one of the addresses from his address book or enter a new delivery address. Only the chosen delivery addresses will be fetched from the ERP.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/ordering_process.md
> +A confirmation email is sent to the customer and the email address which is set in the configuration.
```suggestion
A confirmation email is sent to the customer to the email address which is set in the configuration.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/payment_and_shipping_options.md
> +The payment and shipping method offered can be enabled or disabled per SiteAccess.
```suggestion
The payment and shipping methods can be enabled or disabled per SiteAccess.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/payment_and_shipping_options.md
> +eZ Commerce offers a flexible way to define shipping costs, if this is not set in the ERP system.
```suggestion
eZ Commerce offers a flexible way to define shipping costs, if they are not set in the ERP system.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/payment_and_shipping_options.md
> +In addition it is possible to configure different shipping cost depending on the amount of the basket (including free of freight rules):
```suggestion
In addition it is possible to configure different shipping cost depending on the size of the basket (including free of freight rules):
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/product_description.md
> +eZ Commerce is integrated into eZ Platform and is relying and supporting on eZ Platform functions such as user management, search, content, Page Builder.
```suggestion
eZ Commerce is integrated into eZ Platform and is relying on and supporting eZ Platform functions such as user management, search, content, Page Builder.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/templates_and_design.md
> +4. We use mostly [jQuery](http://jquery.com/) and a bit of [Backbone.js](http://backbonejs.org/) when it comes to JavaScript. Sometime we use plain vanilla JavaScript as well.
```suggestion
4. We use mostly [jQuery](http://jquery.com/) and a bit of [Backbone.js](http://backbonejs.org/) when it comes to JavaScript. We also use plain vanilla JavaScript.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/user_management.md
> +In addition a shop owner gets information about the last orders and the sales statistics of the customer. If a user has a current basket it is displayed as well.
```suggestion
In addition, a shop owner gets information about the last orders and the sales statistics of the customer. If a user has a current basket it is displayed as well.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/product_description/user_management.md
> +Afterwards specific roles can be assigned to the user group. In eZ Commerce new users are created in a given user group. The location ID of the user group is configured in a yml file.
```suggestion
Afterwards specific Roles can be assigned to the User Group. In eZ Commerce new users are created in a given User Group. The location ID of the User Group is configured in a yml file.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/rate_and_review/rate_and_review.md
> +Rate and review is a component to assign a rate of stars (1 to 5) and a review or comment to eZ Commerce products.
```suggestion
Rate and review is a component that assigns a rate of stars (1 to 5), a review or a comment to eZ Commerce products.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/rate_and_review/rate_and_review.md
> +In eZ Commerce backend there is a simple module to manage user rate and reviews.
```suggestion
In eZ Commerce backend there is a simple module that manages user rates and reviews.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/search/search_configuration/solr_schema_configuration.md
> +eZ Commerce is using an adapted schema definition which is installed using the shell script install-solr.sh.
```suggestion
eZ Commerce is using an adapted schema definition which is installed using the shell script `install-solr.sh`.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/guide/user_management/customer_center/customer_center_budget_workflow.md
> +Customer Center comes with standard handling for budget workflow. If the user of customercenter has a defined budget, that can not be exceeded (e.g. budget per order, budget per month), eZ Commerce w
```suggestion
Customer Center comes with standard handling for budget workflow. If the user of Customer Center has a defined budget, that can not be exceeded (e.g. budget per order, budget per month), eZ Commerce will check the budget during the checkout process.
```

2020-05-12 08:13 UTC, MagdalenaZuba commented on docs/user_manual/plugins_and_addons/customer_center.md
>  The extra module „Customer Center“ maps customer specific business processes and makes them available in the online shop
```suggestion
The extra module "Customer Center" maps customer specific business processes and makes them available in the online shop:
```

2020-05-12 08:39 UTC, DominikaK commented on docs/getting_started/first_steps.md
> +# First steps
This is to mirror what we have in developer-doc: https://doc.ezplatform.com/en/master/getting_started/first_steps/

2020-05-12 08:40 UTC, DominikaK commented on docs/getting_started/requirements.md
> +## Client
Here also, done with dev-doc as model: https://doc.ezplatform.com/en/master/getting_started/requirements/

2020-05-12 08:54 UTC, DominikaK commented on docs/guide/basket/basket.md
> +Configuration controls which Fields from the product are stored.
It's a domain term from the content model

2020-05-12 11:46 UTC, MagdalenaZuba approved these changes

2020-05-13 06:19 UTC, dabrt approved these changes

2020-05-13 06:20 UTC, merged