[WIP] Installation instruction
ezsystems/commerce-documentation pull request #20
Opened 2020-08-05 06:39 UTC by DominikaK

Note: this duplicates the content from https://doc.ezplatform.com/en/master/getting_started/install_ez_platform/ and https://doc.ezplatform.com/en/master/getting_started/install_ez_enterprise/ **on purpose**  until we have one joint installation doc

To do:
- [ ] Add recommended Solr setup

2020-08-05 13:01 UTC, SylvainGuittard approved these changes

2020-08-10 07:23 UTC, bogusez approved these changes

2020-08-21 16:32 UTC, dabrt requested changes

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    Installation for production is only supported on Linux.
```suggestion
    Installation for the production purposes is only supported on Linux.
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +## Prepare work environment
```suggestion
## Prepare the work environment
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +To use search in the front end, you need to have [Solr installed](#install-solr).
1. Does commerce support other search engines, like elastic?
2. Would it look better if there was a simple bulleted list with installation prerequisites instead of separate sentences?

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +Use the package manager for your Linux distribution. For example on Ubuntu:
```suggestion
Use the package manager for your Linux distribution. 
For example, on Ubuntu:
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +To verify you got a recent stable version of Composer, you can run:
```suggestion
To verify that you have the most recent stable version of Composer, you can run:
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    After this you need to replace `composer` with `php -d memory_limit=-1 composer.phar` in all commands below.
```suggestion
    If you do so, you must replace `composer` with `php -d memory_limit=-1 composer.phar` in all commands below.
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +in eZ Platform installation to learn how to authenticate yourself for commercial packages.
```suggestion
to learn about authenticating yourself for commercial packages.
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +In order to install a new project using `composer create-project` to get latest version of eZ Commerce,
```suggestion
In order to install a new project with `composer create-project` to get the latest version of eZ Commerce,
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +you'll need to tell Composer which token to use before the project folder is created in the first place.
```suggestion
you must first inform the Composer, which token to use before the project folder is created.
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    If you started with a trial installation, you should [adjust the channel(s)](#edit-composerjson) you use in order to get software under [BUL license instead of a TTL license](https://ibexa.co/Abo
```suggestion
    If you started with a trial installation, you must [adjust the channel(s)](#edit-composerjson) you use in order to get software under [BUL license instead of a TTL license](https://ibexa.co/About-our-Software/Licenses-and-agreements/).
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +## Edit composer.json
If this paragraph relates to the note above, it would be a good idea to turn a note into a separate section "Changing the licensing scheme", with an introductory pargraph and steps needed to switch to the commercial license.

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +Alternatively, you can also change individual installation parameters in `.env`.
"Alternatively" to "also" what?
Would it be:
"You can also use the `.env` file to set a number of individual installtion parameters, listed below."

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    It is recommended to store the database credentials in your `.env.local` file and not commit it to the Version Control System.
```suggestion
    Do not store the database credentials in your `.env.local` file, nor commit them to the Version Control System.
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +- `DATABASE_VERSION` - set to your version if it is different than the default
Do you need the "if different..." part?
Other places in the documentation say:
"- database server version (for a MariaDB database, prefix the value with mariadb-)"

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +eZ Commerce requires Solr as search engine. To install it, run the included script:
```suggestion
eZ Commerce requires Solr as a search engine. To install it, run the included script:
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +In the `.env` file configure the following parameters to your Solr values:
```suggestion
Configure the following parameters in the `.env` file:
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +Also in `.env` set Solr as the search engine:
```suggestion
Also in the `.env` file, set Solr as the search engine:
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +## Create database
```suggestion
## Create a database
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    You can omit this step. If you do not create a database now, it will be created automatically in the next step.
If this step is obsolete, because the DB is created automatically anyway, can we simply get rid of it? The less ambiguity, the better. Also, the next sentence is redundant, the readers have just set the parameters two paragraphs above.

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +Before executing it make sure that the database user has sufficient permissions.
How do I check it? Can you link to a paragraph that explains this?

Also, if we removed the preceding step, we could easily remove the "if you had not created it earlier" loop.

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +This operation is performed only once when you install eZ Commerce for the first time.
```suggestion
This operation is performed only once, when you install eZ Commerce for the first time.
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +!!! tip "Enabling Link manager"
```suggestion
!!! tip "Enabling the Link manager"
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    To make use of [Link Manager](../guide/url_management.md), you need to [set up cron](../guide/url_management.md#enable-automatic-url-validation).
```suggestion
    To make use of the [Link Manager](../guide/url_management.md), you must [set up cron](../guide/url_management.md#enable-automatic-url-validation).
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +## Prepare installation for production
```suggestion
## Prepare an installation for production
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +For development needs, the web user can be made the owner of all your files (for example with the `www-data` web user):
```suggestion
For development needs, the web server user can be the owner of all your files (for example the `www-data` web user):
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +Directories `var` and `public/var` need to be writable by CLI and web server user.
```suggestion
Directories `var` and `public/var` need to be writable by CLI and the web server user.
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    For security reasons, in production web server should not have write access to other directories than `var`. Skip the step above and follow the link below for production needs instead.
```suggestion
    For security reasons, in production, the web server should not have write access to other directories than `var`. Skip the step above and follow the link below for production needs instead.
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    You must also make sure that the web server cannot interpret files in the `var` directory through PHP. To do so, follow the instructions on [setting up a virtual host below](#set-up-virtual-host)
```suggestion
    You must also make sure that the web server cannot interpret files in the `var` directory through PHP. 
    To do so, follow the instructions on [setting up a virtual host below](#set-up-virtual-host).
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +### Set up virtual host
```suggestion
### Set up a virtual host
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +Modify it to fit your project.
```suggestion
Modify the file to fit your project.
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +depending on the environment you want:
```suggestion
depending on the environment that you are configuring:
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +#### Enable virtual host
```suggestion
#### Enable the virtual host
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +Finally, restart the Apache server. The command may vary depending on your Linux distribution. For example of Ubuntu use:
```suggestion
Finally, restart the Apache server. 
The command may vary depending on your Linux distribution. 
For example, on Ubuntu use:
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    If you want to get your eZ Commerce installation up and running quickly,
```suggestion
    To get your eZ Commerce installation up and running quickly,
```

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    you can use Docker-based [eZ Launchpad](https://ezsystems.github.io/launchpad/), supported by the eZ Community,
```suggestion
    use the Docker-based [eZ Launchpad](https://ezsystems.github.io/launchpad/), which takes care of the whole setup for you.

2020-08-21 16:32 UTC, dabrt commented on docs/getting_started/install_ez_commerce.md
> +    which takes care of the whole setup for you.
```suggestion
    eZ Launchpad is supported by the eZ Community.
```

2020-08-31 10:11 UTC, DominikaK commented on docs/getting_started/install_ez_commerce.md
> +In order to install a new project using `composer create-project` to get latest version of eZ Commerce,
```suggestion
In order to install a new project using `composer create-project` to get the latest version of eZ Commerce,
```

2020-08-31 10:13 UTC, DominikaK commented on docs/getting_started/install_ez_commerce.md
> +- `DATABASE_VERSION` - set to your version if it is different than the default
```suggestion
- `DATABASE_VERSION` - database server version (for a MariaDB database, prefix the value with `mariadb-`)
```
as per the latest change to main installation guide

2020-08-31 10:17 UTC, DominikaK commented on docs/getting_started/install_ez_commerce.md
> +To use search in the front end, you need to have [Solr installed](#install-solr).
Commerce does not support Elastic yet, AFAIK. will probably change it to bullet points after merging with the main installation guide.

2020-08-31 10:18 UTC, DominikaK commented on docs/getting_started/install_ez_commerce.md
> +Alternatively, you can also change individual installation parameters in `.env`.
```suggestion
Instead of setting `DATABASE_URL`, you can change individual installation parameters in `.env`.
```

2020-09-03 08:05 UTC, dabrt approved these changes
Please consider implementing comments in the future

2020-09-03 08:08 UTC, merged