One-page form revision
ezsystems/commerce-documentation pull request #23
Opened 2020-08-10 13:19 UTC by DominikaK

https://jira.ez.no/browse/EC-219

"Implement custom one-page form" hidden until it can be verified and rewritten to current codebase.

2020-08-21 14:33 UTC, dabrt requested changes

2020-08-21 14:33 UTC, dabrt commented on docs/guide/checkout/checkout_features/rma_process.md
> +After the user submits the form, an email is sent to the admin using [SendCancellationEmailDataProcessor](../../forms/form_api/dataprocessors.md#sendcancellationemaildataprocessor).
```suggestion
After a user submits the form, an email is sent to the admin by using [SendCancellationEmailDataProcessor](../../forms/form_api/dataprocessors.md#sendcancellationemaildataprocessor).
```

2020-08-21 14:33 UTC, dabrt commented on docs/guide/checkout/checkout_features/rma_process.md
> +eZ Commerce also offers an online RMA form. After user submits this form, an email is sent to admin using [SendRmaEmailDataProcessor](../../forms/form_api/dataprocessors.md#sendrmaemaildataprocessor)
```suggestion
eZ Commerce also offers an online RMA form. 
After a user submits the form, an email is sent to the admin by using [SendRmaEmailDataProcessor](../../forms/form_api/dataprocessors.md#sendrmaemaildataprocessor).
```

2020-08-21 14:33 UTC, dabrt commented on docs/guide/forms/form_api/form_api.md
> +Because every form entity is a custom class, when the form is passed to `AbstractDataProcessor`,
```suggestion
Every form entity is a custom class, therefore, when the form is passed to `AbstractDataProcessor`,
```

2020-08-21 14:33 UTC, dabrt commented on docs/guide/forms/form_api/form_api.md
> +The [VIES web-service (SOAP)](http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl) of the European Commission is used. The condition for validation is that the VAT number contains the coun
```suggestion
The [VIES web-service (SOAP)](http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl) of the European Commission is used. 
A condition for validation is that the VAT number contains a country code.
```

2020-08-21 14:33 UTC, dabrt commented on docs/guide/forms/form_api/predataprocessors.md
> +The `use_single_name_field` setting defines if first name and surname from the form are stored in one or two separate fields:
```suggestion
The `use_single_name_field` setting defines whether the first name and surname from the form are stored in one or two separate fields:
```

2020-08-21 14:33 UTC, dabrt commented on docs/guide/forms/forms.md
> +The process that pre-fills the form is called [`preDataProcessor`](form_api/predataprocessors.md).
I'd consider using the name "pre-data processor" nad not the actual name of the processor class here.

2020-08-21 14:33 UTC, dabrt commented on docs/guide/forms/forms.md
> +These actions are services that are called is a sequence and are able to exchange the data.
```suggestion
These actions are services that are called in a sequence and are able to exchange the data.
```

"exchange" -> "replace" ?

2020-08-21 14:33 UTC, dabrt commented on docs/guide/forms/forms.md
> +|`modelClass`|Required. Fully-qualified class path to the form entity. This class must extend `Silversolutions\Bundle\EshopBundle\Entities\Forms\AbstractFormEntity`|
```suggestion
|`modelClass`|Required. A fully-qualified class path to the form entity. This class must extend `Silversolutions\Bundle\EshopBundle\Entities\Forms\AbstractFormEntity`|
```

2020-08-21 14:33 UTC, dabrt commented on docs/guide/forms/forms.md
> +|`typeClass`|Required if `typeService` is not defined. Fully-qualified class path to the form type. Using `typeService` gives more flexibility.|
```suggestion
|`typeClass`|Required if `typeService` is not defined. A fully-qualified class path to the form type. Using `typeService` gives more flexibility.|
```

2020-08-31 08:46 UTC, DominikaK commented on docs/guide/forms/forms.md
> +The process that pre-fills the form is called [`preDataProcessor`](form_api/predataprocessors.md).
```suggestion
The process that pre-fills the form is called a [pre-data processor](form_api/predataprocessors.md).
```

2020-08-31 10:14 UTC, dabrt approved these changes

2020-08-31 11:51 UTC, merged