Landing page revision
ezsystems/commerce-documentation pull request #24
Opened 2020-08-11 11:10 UTC by DominikaK

2020-08-11 11:28 UTC, dew326 approved these changes

2020-08-21 13:00 UTC, dabrt requested changes

2020-08-21 13:00 UTC, dabrt commented on docs/guide/page.md
> +eZ Commerce adds the following blocks for the Page Builder:
```suggestion
eZ Commerce adds the following blocks to the Page Builder:
```

2020-08-21 13:00 UTC, dabrt commented on docs/guide/page.md
> +![Page](img/page_1.png)
```suggestion
![Page](img/landing_page_1.png)  
```
Also, last time I spoke to Magda, she insisted that all images should have a caption.

2020-08-21 13:00 UTC, dabrt commented on docs/guide/page.md
> +
```suggestion

To display a list of recently viewed products, place the following code in a template:

```

2020-08-21 13:00 UTC, dabrt commented on docs/guide/page.md
> +The controller is able to render a different template if required (parameter template).
```suggestion
The controller is able to render a different template if required (a parameter template).
```

2020-08-21 13:00 UTC, dabrt commented on docs/guide/page.md
> +You can configure the maximum number of last viewed products in configuration
```suggestion
You can configure the maximum number of last viewed products by selecting
```

2020-08-21 13:00 UTC, dabrt commented on docs/guide/page.md
> +in **eCommerce** -> **Configuration Settings** -> **Catalog** -> **Last viewed product limit**.
```suggestion
**eCommerce** -> **Configuration Settings** -> **Catalog** -> **Last viewed product limit**.
```

2020-08-31 08:39 UTC, DominikaK commented on docs/guide/page.md
> +![Page](img/page_1.png)
I changed the file name to correspond to current naming (see top of the diff).
Also, I think we must have an alt text for every image, but not a caption, when the surrounding text is clear.

2020-08-31 09:54 UTC, dabrt commented on docs/guide/page.md
> +![Page](img/page_1.png)
Now I see what you mean. We must then discuss the caption idea in the afternoon. However, the two images are different and the new one does not clearly show the three block types. Can we go back to it later and pick a clearer example?

2020-08-31 10:04 UTC, DominikaK commented on docs/guide/page.md
> +![Page](img/page_1.png)
Definitely, best after the next release.

2020-08-31 10:16 UTC, dabrt approved these changes

2020-08-31 11:51 UTC, merged