Comparison, Wishlist and Translation revision
ezsystems/commerce-documentation pull request #26
Opened 2020-09-11 09:57 UTC by DominikaK

https://jira.ez.no/browse/EC-219

Most parts of the UI-related doc removed, as they will have to be rewritten from scratch for the user guide anyway.

2020-09-15 13:57 UTC, dabrt requested changes

2020-09-15 13:57 UTC, dabrt commented on docs/guide/product_comparison/product_comparison.md
> +    It is recommended to use a service to frequently clean old anonymous comparison lists for sites with heavy traffic.
```suggestion
    It is recommended that you use a service to frequently clean old anonymous comparison lists for sites with heavy traffic.
```

2020-09-15 13:57 UTC, dabrt commented on docs/guide/product_comparison/product_comparison.md
> +No prices and no product quantity are stored in the comparison list.
```suggestion
Neither prices nor product quantity details are stored in the comparison list.
```

2020-09-15 13:57 UTC, dabrt commented on docs/guide/product_comparison/product_comparison.md
> +The list is divided into categories per kind of product.
```suggestion
The list is divided into categories by product type.
```

2020-09-15 13:57 UTC, dabrt commented on docs/guide/product_comparison/product_comparison.md
> +There is an icon in top left corner to show/hide attributes.
```suggestion
There is an icon in the top left corner to show/hide the attributes.
```

2020-09-15 13:57 UTC, dabrt commented on docs/guide/product_comparison/product_comparison.md
> +If `collapse_attributes` is set to true, hiding/showing the same attributes is enabled.
```suggestion
If `collapse_attributes` is set to true, hiding/showing attributes with the same value is enabled.
```

2020-09-15 13:57 UTC, dabrt commented on docs/guide/product_comparison/product_comparison_api.md
> +The `getComparisonCategory()` method takes a catalog element (including products) as an argument.
(including products)
Is it "that includes products" or "products included"?

2020-09-15 13:57 UTC, dabrt commented on docs/guide/product_comparison/product_comparison_templates.md
>  |`parts/user_menu.html.twig`|HTML content for right user menu navigation with links to comparison|
```suggestion
|`parts/user_menu.html.twig`|HTML content for the right-hand user menu navigation with links to a comparison|
```

2020-09-15 13:57 UTC, dabrt commented on docs/guide/translations.md
> +When you use Symfony translations instead of text modules, you can use a message with placeholders
```suggestion
When you use Symfony translation service instead of text modules, you can use a message with placeholders
```

2020-09-15 13:57 UTC, dabrt commented on docs/guide/translations.md
> +If it finds no translations, the [standard Symfony translation service](http://symfony.com/doc/3.4/book/translation.html) is used.
```suggestion
If it does not find any translations, the [standard Symfony translation service](http://symfony.com/doc/3.4/book/translation.html) is used.
```

2020-09-15 13:57 UTC, dabrt commented on docs/guide/translations.md
> +| Identifier | The source or identifier for translation that has to be defined. |
```suggestion
| Identifier | The source or identifier for the translation that has to be defined. |
```

2020-09-15 13:57 UTC, dabrt commented on docs/guide/wishlist_and_stored_baskets.md
> +|`Basket/show_wishlist_part.html.twig`|Partial page responsible for rendering the wishlist page|
```suggestion
|`Basket/show_wishlist_part.html.twig`|Partial page responsible for rendering the wishlist|
```

2020-09-15 13:57 UTC, dabrt commented on docs/guide/wishlist_and_stored_baskets.md
> +`get_stored_baskets()` returns stored baskets for current user:
```suggestion
`get_stored_baskets()` returns stored baskets for the current user:
```

2020-09-15 14:16 UTC, DominikaK commented on docs/guide/product_comparison/product_comparison_api.md
> +The `getComparisonCategory()` method takes a catalog element (including products) as an argument.
```suggestion
The `getComparisonCategory()` method takes a catalog element (products included) as an argument.
```

2020-09-15 14:16 UTC, DominikaK commented on docs/guide/product_comparison/product_comparison.md
> +The list is divided into categories per kind of product.
"Product type" can be misleading here, because it is a domain term, and the "kind" here can also refer to a product category

2020-09-16 08:39 UTC, dabrt commented on docs/guide/product_comparison/product_comparison.md
> +The list is divided into categories per kind of product.
The term "product type" is used in other places above, hence a suggestion to maintain consistency.

2020-09-16 08:43 UTC, DominikaK commented on docs/guide/product_comparison/product_comparison.md
> +Comparison lists are divided per product type (separately for, e.g. sofas, tables, etc.).
```suggestion
Comparison lists are divided per kind of product (separately for, e.g. sofas, tables, etc.). 
```

2020-09-16 08:44 UTC, DominikaK commented on docs/guide/product_comparison/product_comparison.md
> +The list is divided into categories per kind of product.
Also fixed above: https://github.com/ezsystems/commerce-documentation/pull/26/files#diff-d95a9ad2aafe8c40cd5fab965e5f94c6R5

2020-09-16 12:22 UTC, dabrt approved these changes

2020-09-16 13:06 UTC, merged