Minor guide sections
ezsystems/commerce-documentation pull request #6
Opened 2020-05-28 08:55 UTC by DominikaK

2020-06-01 14:20 UTC, MagdalenaZuba requested changes

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/modifying_the_search_query.md
> +The `PostBuildEzContentQueryEvent` event is thrown just before content model content for the navigation is fetched.
```suggestion
The `PostBuildEzContentQueryEvent` event is thrown just before content model for the navigation is fetched.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation.md
> +which introduces the products for the shop, for example:
```suggestion
which adds products to the shop, for example: 
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation.md
> +The navigation can also store any additional data in the navigation node.
```suggestion
The navigation can also store additional data in the navigation node.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation.md
> +    If you want to have the same categories on several places, you need to copy the content.
```suggestion
    If you want to have the same categories in several places, you need to copy the content.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation.md
> +The following data must at least be indexed:
```suggestion
The following data must be indexed:
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation.md
> +By default navigation is cached by `user-hash` for 10 hours.
```suggestion
By default navigation is cached by `user-hash` every 10 hours.
```
not sure?

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation.md
> +|Root node|`root_node`|Root Location of the product catalog in the storage engine|
```suggestion
|Root node|`root_node`|Root Location of the product catalog in the storage engine.|
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation.md
> +|Depth|`depth`|The depth of the product catalog. The navigation is built using this parameter. A depth of 1 means that there is just one level starting at "Root node"|
```suggestion
|Depth|`depth`|The depth of the product catalog. The navigation is built using this parameter. A depth of 1 means that there is just one level starting at "Root node".|
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation_configuration.md
> +To change the time for which navigation is cached, set the `router_cache_ttl` parameter (in seconds):
```suggestion
To change the navigation cache time, set the `router_cache_ttl` parameter (in seconds):
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation_configuration.md
> +This does not include the product catalog, which has it's own depth specified.
```suggestion
This does not include the product catalog, which has its own depth specified.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation_configuration.md
> +Use `navigation_sort_order` to set the order or sorting by priority, ascending or descending:
```suggestion
Use `navigation_sort_order` to set the order or sorting by priority to ascending or descending:
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation_configuration.md
> +Then you can additionally store the image in the navigation node and output it on the site:
```suggestion
Then you can additionally store the image in the navigation node and display it on the site:
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/navigation/navigation_templates.md
> +Returns a comma separated string of data_locations of the given element. All parent locations incl. the element location are returned. These data_locations are used to highlight the active node in th
```suggestion
Returns a comma separated string of `data_locations` of the given element. All parent Locations including the element Location are returned. These `data_locations` are used to highlight the active node in the navigation.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/additional_newsletter_data.md
> +that listens to `subscribe_newsletter_event` or  `update_newsletter_event`.
```suggestion
that listens to `subscribe_newsletter_event` or `update_newsletter_event`.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter.md
> +Only a newsletter provider service with specific API implementation of this provider has to be implemented.
```suggestion
A newsletter provider service with specific API implementation of this provider has to be implemented separately.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter.md
> +    - `order_amount_total` - total amount for the user
```suggestion
    - `order_amount_total` - total order amount for the user
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter.md
> +Attributes that do not exist in the newsletter provider has to be created first.
```suggestion
Attributes that do not exist in the newsletter provider have to be created first.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter.md
> +If they is logged in, they can immediately update the status in their profile.
```suggestion
If they are logged in, they can immediately update the status in their profile.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter2go/newsletter2go.md
> +The Newsletter2Go plugin integrates the newsletter service https://www.newsletter2go.de into the API.
```suggestion
The Newsletter2Go plugin integrates the newsletter service https://www.sendinblue.com/newsletter2go/ into the API.
```
Newsletter2Go's has a new name since 14 April 2020: Sendinblue

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter2go/newsletter2go.md
> +One address books equals one newsletter topic, so the user can choose if they want to subscribe to different topics separately.
```suggestion
One address book equals one newsletter topic, so the user can choose if they want to subscribe to different topics separately.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter2go/newsletter2go_cookbook/custom_newsletter2go_functions.md
> +If you need to implement custom functions to extend the newsletter functionality, you can use:
```suggestion
If you need to implement custom functions to extend the newsletter, you can use:
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter2go/newsletter2go_cookbook/sending_additional_data_to_newsletter2go.md
> +Any data can be sent to Newsletter2Go, but custom attributes have to be created first in the Newsletter2Go backend.
```suggestion
To send additional data to Newsletter2Go, you have to also create custom attributes in the Newsletter2Go backend.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter2go/newsletter2go_cookbook/working_with_several_newsletters.md
> +2\. Behind every newsletter topic the address book ID must be configured.
```suggestion
2\. Configure the address book ID for every newsletter topic.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter2go/newsletter2go_cookbook/working_with_several_newsletters.md
> +5\. The user can be created in selected address books:
```suggestion
5\. Create a user in the selected address books:
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter_interface.md
> +otherwise the required attributes must be specified in $params.
```suggestion
otherwise the required attributes must be specified in `$params`.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter_interface.md
> +The `getEmail` method returns the correct email address.
```suggestion
The `getEmail` method returns the email address.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter_interface.md
> +If `CustomerProfileData` is provided, the email from `SesUser` has to be used
```suggestion
If `CustomerProfileData` is provided, the email from `SesUser` will be used.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter_interface.md
> +If `CustomerProfileData` is not provided, the email from `$params` has to be used
```suggestion
If `CustomerProfileData` is not provided, the email from `$params` will be used.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/newsletter/newsletter_interface.md
> +(e.g. through the double opt-in process)
```suggestion
(e.g. through the double opt-in process).
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/product_comparison/product_comparison.md
> +Comparison lists are divided per product type (for example, like speakers, microphones, etc.).
```suggestion
Comparison lists are divided per product type (for example speakers, microphones, etc.). 
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/product_comparison/product_comparison.md
> +In the next call the customer will see sorted list by his preference.
```suggestion
In the next call the customer will see sorted list by their preference.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/product_comparison/product_comparison_faq.md
> +To change the logic of determining to which categories should be assigned to particular products,
```suggestion
To change the logic that determines to which categories to assign particular products,
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/product_comparison/product_comparison_faq.md
> +First of all the service must implement `ComparisonServiceInterface`.
```suggestion
First, the service must implement `ComparisonServiceInterface`.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/product_comparison/product_comparison_faq.md
> +1. If all else fails, places the product in the default category
```suggestion
1. If everything else fails, places the product in the default category
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/product_comparison/product_comparison_faq.md
> +|Dynamic fields from the `dataMap` attribute|`manufacturer`</br>`manufacturerSku`</br>`color`|These attributes are stored in `dataMap`. They are part of the Technical Information group.</br>Manufactu
```suggestion
|Dynamic fields from the `dataMap` attribute|`manufacturer`</br>`manufacturerSku`</br>`color`|These attributes are stored in `dataMap`. They are part of the Technical Information group.</br>Manufacturer, ManufacturerSku and Color are handled without eZ matrix. The names that should be read from `dataMap` must be configured in the `siso_comparison.<default>.technical_attributes` attribute|
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/product_comparison/product_comparison_faq.md
> +Drag and drop working differently for public and private (customer-specific) lists.
```suggestion
Drag and drop works differently for public and private (customer-specific) lists.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/product_comparison/product_comparison_faq.md
> +In public lists the customer can use drag and drop, but the order is not be saved.
```suggestion
In public lists the customer can use drag and drop, but the order is not saved.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/quickorder/quickorder.md
> +Customers can type SKUs and quantities and either directly add products to the basket by clicking on the **Add to basket** button,
```suggestion
Customers can type SKUs and quantities to either directly add products to the basket by clicking on the **Add to basket** button,
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/quickorder/quickorder.md
> +!!! note
```suggestion
!!! caution
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/quickorder/quickorder.md
> +If a customer leaves the SKU field (for example by choosing one of the autosuggestion result) and sets the cursor on another field (e.g. quantity field or next line), a background search starts which
```suggestion
If a customer leaves the SKU field (for example by choosing one of the autosuggestion result) and sets the cursor on another field (e.g. quantity field or next line), a background search starts. It displays the product name (and variant code) and the unit price.
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/quickorder/quickorder.md
> +    The custom text should be the 4th column.
```suggestion
    In this case, the custom text should be the last column (3rd or 4th).
```

2020-06-01 14:20 UTC, MagdalenaZuba commented on docs/guide/quickorder/quickorder_api.md
> +The fields `ses_variant_\*` are additional fields indexed in the Solr index.
```suggestion
The `ses_variant_\*` fields are additional fields indexed in the Solr.
```

2020-06-02 06:22 UTC, DominikaK commented on docs/guide/navigation/navigation.md
> +By default navigation is cached by `user-hash` for 10 hours.
It's the duration for which the cache is valid

2020-06-02 06:24 UTC, DominikaK commented on docs/guide/newsletter/newsletter_interface.md
> +If `CustomerProfileData` is provided, the email from `SesUser` has to be used
```suggestion
If `CustomerProfileData` is provided, the email from `SesUser` is used.
```

2020-06-02 06:25 UTC, DominikaK commented on docs/guide/newsletter/newsletter_interface.md
> +If `CustomerProfileData` is not provided, the email from `$params` has to be used
If `CustomerProfileData` is not provided, the email from `$params` is used.

2020-06-02 06:29 UTC, MagdalenaZuba approved these changes

2020-06-03 06:23 UTC, merged